Repository magang-mknows/mknows-fe, pull requests merged in 2023-06, with the labels that each got.

#491 bugfix : fix height card on history request dashboard
  apps/cs/src/modules/home/history-request-section.tsx
Labels: bug, CS

#477 improvement: design slicing check result page on CS
  apps/cs/public/assets/request-page/close.webp
  apps/cs/src/modules/request/api.ts
  apps/cs/src/modules/request/check-result/index.tsx
  apps/cs/src/modules/request/check-result/table.tsx
  apps/cs/src/modules/request/hooks.ts
  apps/cs/src/modules/request/process/index.tsx
  apps/cs/src/modules/request/process/table.tsx
  apps/cs/src/modules/request/store.ts
  apps/cs/src/modules/request/types.d.ts
  apps/cs/src/routers/index.tsx
Labels: CS

#507 improvement : fix named file redirects
  apps/cs/public/_redirects
  apps/kg/modules/common/footer/footer-layout/links/links.tsx
  apps/kg/modules/landing-alternatif/article/section.tsx
  apps/kg/modules/landing-alternatif/banner/banner-4/section.tsx
  apps/kg/modules/landing-alternatif/faculty/section.tsx
  apps/kg/modules/landing-alternatif/feature/section.tsx
  apps/kg/modules/landing-alternatif/hero/section.tsx
Labels: documentation, CS

#510 improvement: update check result page and bugfixing card on dahsboard page
  apps/cs/public/assets/alert-circle.webp
  apps/cs/src/modules/home/history-request-section.tsx
  apps/cs/src/modules/request/check-result/index.tsx
  apps/cs/src/modules/request/check-result/table.tsx
Labels: bug, CS

#504 Feature : pelatihanku - quiz
  apps/lxp/modules/mytraining-quiz/section/StartQuiz/Question.tsx
  apps/lxp/modules/mytraining-quiz/section/StartQuiz/types.d.ts
  libs/utils/src/index.ts
  libs/utils/src/service/index.ts
  libs/utils/src/service/local-storage/index.ts
Labels: enhancement, LXP

#511 feature : set up api service for get quiz data
  apps/lxp/modules/mytraining-module/type.d.ts
  apps/lxp/modules/mytraining-quiz/api.ts
  apps/lxp/modules/mytraining-quiz/hooks.ts
  apps/lxp/modules/mytraining-quiz/section/StartQuiz/Question.tsx
  apps/lxp/modules/mytraining-quiz/section/StartQuiz/api.ts
  apps/lxp/modules/mytraining-quiz/section/StartQuiz/hook.ts
  apps/lxp/modules/mytraining-quiz/section/StartQuiz/module.tsx
  apps/lxp/modules/mytraining-quiz/section/StartQuiz/types.d.ts
Labels: enhancement, LXP

#515 fix : error mytraining
  apps/lxp/modules/mytraining-module/api.ts
  apps/lxp/modules/mytraining-module/hooks.ts
  apps/lxp/modules/mytraining-module/main/main.tsx
  apps/lxp/modules/mytraining-module/type.d.ts
  apps/lxp/modules/mytraining-quiz/api.ts
  apps/lxp/modules/mytraining-quiz/home/QuizHome.tsx
  apps/lxp/modules/mytraining-quiz/hooks.ts
  apps/lxp/modules/mytraining-quiz/section/StartQuiz/api.ts
Labels: bug, LXP

#513 fixing : search action on table request process
  apps/cs/src/modules/request/hooks.ts
  apps/cs/src/modules/request/process/index.tsx
  apps/cs/src/modules/request/process/table.tsx
Labels: bug, CS

#517 improvement: quota page
  apps/cs/public/assets/download-bottom.webp
  apps/cs/src/modules/quota/alocation-quota.tsx
  apps/cs/src/modules/quota/history-alocation.tsx
  apps/cs/src/modules/quota/table2.tsx
  apps/cs/src/modules/report/report-request/table.tsx
  apps/cs/src/modules/report/report-user/table.tsx
  apps/cs/src/modules/request/api.ts
  apps/cs/src/modules/request/feature/choice-feature/table.tsx
  apps/cs/src/modules/request/feature/request.tsx
  apps/cs/src/modules/request/hooks.ts
  apps/cs/src/modules/request/process/dummyData.tsx
  apps/cs/src/modules/request/process/index.tsx
  apps/cs/src/modules/request/process/table.tsx
  apps/cs/src/modules/request/process/table2.tsx
  apps/cs/src/modules/request/result/dummyData.tsx
  apps/cs/src/modules/request/result/index.tsx
  apps/cs/src/modules/request/result/table.tsx
  apps/cs/src/modules/request/store.ts
  apps/cs/src/modules/request/types.d.ts
  apps/cs/src/modules/user/hooks.ts
  apps/cs/src/modules/user/store.ts
  apps/cs/src/modules/user/table2.tsx
  apps/cs/src/modules/user/types.ts
Labels: CS

#523 fix : teks on landing, training plan, and doubt mark quiz
  apps/lxp/modules/common/footer/footer-layout/address/address.tsx
  apps/lxp/modules/common/footer/footer-layout/footer.tsx
  apps/lxp/modules/common/footer/footer-layout/links/links.tsx
  apps/lxp/modules/common/provider/ClientProvider/provider.tsx
  apps/lxp/modules/landing/hero/section.tsx
  apps/lxp/modules/mytraining-quiz/hooks.ts
  apps/lxp/modules/mytraining-quiz/section/StartQuiz/Question.tsx
  apps/lxp/modules/training-information/content/header/header.tsx
  apps/lxp/modules/training-information/content/section.tsx
  apps/lxp/modules/training-information/content/table/table.tsx
  apps/lxp/modules/training-plan/header/header.tsx
  apps/lxp/modules/training-plan/main/main.tsx
  apps/lxp/modules/training-plan/taken/section.tsx
  libs/components/atoms/src/inputs/search/index.tsx
  libs/components/molecules/src/navbar/section/top-nav/section.tsx
  libs/components/molecules/src/navbar/section/top-nav/store.ts
  libs/components/molecules/src/navbar/types.ts
Labels: bug, LXP

#542 feature : mystudy assignment integration
  apps/kg/modules/mystudy/assignment/api.ts
  apps/kg/modules/mystudy/assignment/hooks.ts
  apps/kg/modules/mystudy/assignment/index.tsx
  apps/kg/modules/mystudy/assignment/stores.ts
  apps/kg/modules/mystudy/assignment/type.d.ts
  apps/kg/modules/mystudy/module/module-content/pop-up/hooks.ts
  apps/kg/modules/mystudy/mystudy-module/major/section.tsx
  apps/kg/modules/mystudy/subject-details/module.tsx
  apps/kg/next.config.js
Labels: enhancement, KG

#541 Improvemnt : get quiz questions, teks and style revision
  apps/lxp/modules/administrations/module.tsx
  apps/lxp/modules/administrations/section/ContentAdministration/content.tsx
  apps/lxp/modules/administrations/section/TitleAdministration/title.tsx
  apps/lxp/modules/common/footer/footer-layout/address/address.tsx
  apps/lxp/modules/common/footer/footer-layout/footer.tsx
  apps/lxp/modules/common/provider/ClientProvider/provider.tsx
  apps/lxp/modules/contact/container/form/form.tsx
  apps/lxp/modules/contact/container/information/information.tsx
  apps/lxp/modules/contact/module.tsx
  apps/lxp/modules/dashboard/event/section.tsx
  apps/lxp/modules/dashboard/module.tsx
  apps/lxp/modules/landing/catalog/catalog.tsx
  apps/lxp/modules/landing/hero/section.tsx
  apps/lxp/modules/mytraining-quiz/home/QuizHome.tsx
  apps/lxp/modules/mytraining-quiz/home/api.ts
  apps/lxp/modules/mytraining-quiz/home/hooks.ts
  apps/lxp/modules/mytraining-quiz/home/types.d.ts
  apps/lxp/modules/mytraining-quiz/section/StartQuiz/Question.tsx
  apps/lxp/modules/mytraining-quiz/section/StartQuiz/hook.ts
  apps/lxp/modules/mytraining-quiz/section/StartQuiz/types.d.ts
  apps/lxp/modules/score-sertificate/main/section.tsx
  apps/lxp/modules/score-sertificate/score-sertificate.tsx
  apps/lxp/modules/training-information/content/section.tsx
  apps/lxp/modules/training-information/traning-information.tsx
  apps/lxp/modules/training-plan/training-plan.tsx
  apps/lxp/modules/unique-event/UniqueEventModule.tsx
  apps/lxp/pages/pelatihanku/quiz/mulai-quiz/[quizID]/[batchID].tsx
  apps/lxp/tailwind.config.js
  libs/components/atoms/src/bread-crumb/index.tsx
  libs/components/atoms/src/inputs/text/index.tsx
  libs/modules/src/features/content/const.ts
  libs/modules/src/features/content/content.tsx
  libs/modules/src/features/features.tsx
Labels: bug, enhancement, LXP

#540 improvement : integrate my-training video module
  apps/lxp/modules/my-training-video-module/api.ts
  apps/lxp/modules/my-training-video-module/pop-up/api.ts
  apps/lxp/modules/my-training-video-module/pop-up/hooks.ts
  apps/lxp/modules/my-training-video-module/pop-up/index.ts
  apps/lxp/modules/my-training-video-module/pop-up/send.tsx
  apps/lxp/modules/my-training-video-module/pop-up/types.d.ts
  apps/lxp/modules/my-training-video-module/section/ContentSection.tsx
  apps/lxp/modules/my-training-video-module/section/Description.tsx
  apps/lxp/modules/my-training-video-module/section/ListStudy.tsx
  apps/lxp/modules/my-training-video-module/section/YoutubeSection.tsx
  apps/lxp/modules/my-training-video-module/section/hooks.ts
  apps/lxp/modules/my-training-video-module/store.ts
  apps/lxp/modules/my-training-video-module/type.d.ts
  apps/lxp/modules/mytraining-module/main/main.tsx
  apps/lxp/modules/mytraining-module/type.d.ts
  apps/lxp/pages/pelatihanku/modul/[subjectID]/[moduleID]/[videoID].tsx
  apps/lxp/pages/pelatihanku/modul/[subjectID]/[moduleID]/index.tsx
  apps/lxp/pages/pelatihanku/modul/video-module/[videoId].tsx
Labels: LXP

#551 adding font monsterat
  apps/lxp/modules/common/provider/ClientProvider/provider.tsx
  apps/lxp/pages/_app.tsx
  apps/lxp/tailwind.config.js
Labels: LXP

#552 improvement: set all administration
  apps/kg/modules/administration/common/section.tsx
  apps/kg/modules/administration/enum.ts
  apps/kg/modules/administration/private-information/index.tsx
  apps/kg/modules/administration/title-information/index.tsx
  apps/kg/modules/administration/types.d.ts
  apps/kg/pages/_app.tsx
  apps/kg/tailwind.config.js
  libs/components/atoms/src/bread-crumb/index.tsx
Labels: enhancement, KG

#543 improvement: spacing col on all tables cs, update download button on expandable row, and card cs moved to libs with name CardCS
  apps/cs/src/components/organisms/card-chart/skor-section.tsx
  apps/cs/src/components/organisms/modal/index.tsx
  apps/cs/src/components/organisms/sidebar/index.tsx
  apps/cs/src/components/organisms/sidebar/sidebar-skeleton.tsx
  apps/cs/src/layouts/base/index.tsx
  apps/cs/src/modules/home/history-request-section.tsx
  apps/cs/src/modules/quota/alocation-quota.tsx
  apps/cs/src/modules/quota/history-alocation.tsx
  apps/cs/src/modules/quota/index.tsx
  apps/cs/src/modules/quota/loading.tsx
  apps/cs/src/modules/quota/table.tsx
  apps/cs/src/modules/quota/table2.tsx
  apps/cs/src/modules/report/index.tsx
  apps/cs/src/modules/report/report-request/index.tsx
  apps/cs/src/modules/report/report-request/table.tsx
  apps/cs/src/modules/report/report-user/table.tsx
  apps/cs/src/modules/request/check-result/index.tsx
  apps/cs/src/modules/request/check-result/table.tsx
  apps/cs/src/modules/request/feature/choice-feature/table.tsx
  apps/cs/src/modules/request/feature/request.tsx
  apps/cs/src/modules/request/index.tsx
  apps/cs/src/modules/request/loading.tsx
  apps/cs/src/modules/request/process/dummyData.tsx
  apps/cs/src/modules/request/process/index.tsx
  apps/cs/src/modules/request/process/table.tsx
  apps/cs/src/modules/request/result/index.tsx
  apps/cs/src/modules/request/result/table.tsx
  apps/cs/src/modules/request/types.d.ts
  apps/cs/src/modules/user/dummyData.tsx
  apps/cs/src/modules/user/table.tsx
  apps/cs/tailwind.config.js
  apps/kg/modules/assignment/component/assignment-card.tsx
  apps/kg/modules/discussion-room/content/post/modal/post-create/section.tsx
  libs/components/molecules/src/card-cs/index.tsx
  libs/components/molecules/src/card-cs/types.d.ts
  libs/components/molecules/src/index.ts
Labels: CS

#555 fix: kg - validasi password
  apps/kg/modules/auth/register/module.tsx
Labels: bug, KG

#554 feature : slicing login admin cs
  apps/cs-admin/postcss.config.js
  apps/cs-admin/public/logo.svg
  apps/cs-admin/src/layout/auth.tsx
  apps/cs-admin/src/module/auth/login/index.tsx
  apps/cs-admin/src/pages/auth/login.tsx
  apps/cs-admin/src/routers/index.tsx
  apps/cs-admin/vite.config.ts
  apps/cs/src/modules/user/hooks.ts
Labels: enhancement, CS

#533 feature : draft KRS
  apps/kg/modules/study-contract/details/draft-krs/api.ts
  apps/kg/modules/study-contract/details/draft-krs/hook.ts
  apps/kg/modules/study-contract/details/draft-krs/store.ts
  apps/kg/modules/study-contract/details/draft-krs/tabel.tsx
  apps/kg/modules/study-contract/details/draft-krs/type.d.ts
  apps/kg/modules/study-contract/details/kontrak-krs/api.ts
Labels: enhancement, KG

#558 Improvement : delete asset unusable and fix import image on project cs
  apps/cs/public/assets/Shape.webp
  apps/cs/public/assets/Vector.webp
  apps/cs/public/assets/check-circle.svg
  apps/cs/public/assets/checklist.svg
  apps/cs/public/assets/logo.webp
  apps/cs/public/assets/pdf.svg
  apps/cs/public/assets/quota/phone-information.webp
  apps/cs/public/assets/request-page/alert-circle.webp
  apps/cs/public/download-bottom.webp
  apps/cs/src/components/organisms/sidebar/index.tsx
  apps/cs/src/modules/quota/alocation-quota.tsx
  apps/cs/src/modules/quota/history-alocation.tsx
  apps/cs/src/modules/quota/index.tsx
  apps/cs/src/modules/report/report-request/table.tsx
  apps/cs/src/modules/report/report-user/table.tsx
  apps/cs/src/modules/request/check-result/index.tsx
  apps/cs/src/modules/request/result/table.tsx
Labels: documentation, CS

#559 improvement : add dummy data on table report coz endpoint from be unready
  apps/cs/src/modules/report/store.ts
Labels: documentation, CS

#560 improve: working otp
  apps/kg/modules/auth/otp/api.ts
  apps/kg/modules/auth/otp/hooks.ts
  apps/kg/modules/auth/otp/index.ts
  apps/kg/modules/auth/otp/module.tsx
  apps/kg/modules/auth/otp/store.ts
  apps/kg/modules/auth/otp/types.ts
  apps/kg/modules/auth/register/module.tsx
  libs/components/molecules/src/popup-modal/index.tsx
  package.json
  yarn.lock
Labels: KG

#568 Feature : submit quiz answer
  apps/kg/modules/study-contract/details/draft-krs/api.ts
  apps/kg/modules/study-contract/details/draft-krs/hook.ts
  apps/kg/modules/study-contract/details/draft-krs/store.ts
  apps/kg/modules/study-contract/details/draft-krs/type.d.ts
  apps/lxp/.env.example
  apps/lxp/modules/mytraining-quiz/section/StartQuiz/Question.tsx
  apps/lxp/modules/mytraining-quiz/section/StartQuiz/api.ts
  apps/lxp/modules/mytraining-quiz/section/StartQuiz/hook.ts
  apps/lxp/modules/mytraining-quiz/section/StartQuiz/types.d.ts
  apps/lxp/tailwind.config.js
  libs/utils/src/service/local-storage/index.ts
Labels: bug, enhancement, LXP

#569 feature : lxp auth otp
  apps/lxp/modules/auth/login/login-popup/login-popup.tsx
  apps/lxp/modules/auth/login/module.tsx
  apps/lxp/modules/auth/otp/api.ts
  apps/lxp/modules/auth/otp/hooks.ts
  apps/lxp/modules/auth/otp/index.ts
  apps/lxp/modules/auth/otp/module.tsx
  apps/lxp/modules/auth/otp/store.ts
  apps/lxp/modules/auth/otp/types.ts
  apps/lxp/modules/auth/register/module.tsx
  apps/lxp/modules/common/provider/ClientProvider/provider.tsx
  apps/lxp/modules/dashboard/event/section.tsx
  libs/modules/src/features/features.tsx
Labels: bug, enhancement, LXP

#571 Improvement : fix tab link use query params
  apps/cs/public/exampe.png
  apps/cs/src/main.tsx
  apps/cs/src/modules/common/hooks.ts
  apps/cs/src/modules/home/history-request-section.tsx
  apps/cs/src/modules/quota/index.tsx
  apps/cs/src/modules/report/index.tsx
  apps/cs/src/modules/request/check-result/index.tsx
  apps/cs/src/modules/request/check-result/table.tsx
  apps/cs/src/modules/request/index.tsx
  apps/cs/src/modules/request/process/dummyData.tsx
  apps/cs/src/modules/request/process/index.tsx
  apps/cs/src/modules/request/process/table.tsx
  apps/cs/src/modules/request/result/index.tsx
  apps/cs/src/modules/request/result/table.tsx
  apps/cs/src/modules/user/add-data/add-data.tsx
  apps/cs/src/modules/user/add-data/ai-capability-scoring/index.tsx
  apps/cs/src/modules/user/add-data/ai-character-scoring/index.tsx
  apps/cs/src/modules/user/add-data/ai-identity-scoring/index.tsx
  apps/cs/src/modules/user/api.ts
  apps/cs/src/modules/user/dummyData.tsx
  apps/cs/src/modules/user/edit-data/ai-capability-scoring/index.tsx
  apps/cs/src/modules/user/edit-data/ai-character-scoring/index.tsx
  apps/cs/src/modules/user/edit-data/ai-identity-scoring/index.tsx
  apps/cs/src/modules/user/edit-data/api.ts
  apps/cs/src/modules/user/edit-data/edit-data.tsx
  apps/cs/src/modules/user/edit-data/hooks.ts
  apps/cs/src/modules/user/edit-data/types.ts
  apps/cs/src/modules/user/hooks.ts
  apps/cs/src/modules/user/table.tsx
  apps/cs/src/routers/index.tsx
  libs/components/atoms/src/cs/icons/ic-delete.tsx
Labels: documentation, CS

#573 improvement: update Quota Page
  apps/cs/src/modules/quota/alocation-quota.tsx
  apps/cs/src/modules/request/feature/request.tsx
  apps/cs/src/modules/request/types.d.ts
  apps/cs/src/modules/user/table.tsx
Labels: CS

#574 Feature : quiz history
  apps/lxp/modules/index.ts
  apps/lxp/modules/mytraining-quiz/home/QuizHome.tsx
  apps/lxp/modules/mytraining-quiz/section/AfterQuiz/QuizHistory/HistoryCard.tsx
  apps/lxp/modules/mytraining-quiz/section/AfterQuiz/QuizHistory/api.ts
  apps/lxp/modules/mytraining-quiz/section/AfterQuiz/QuizHistory/hook.ts
  apps/lxp/modules/mytraining-quiz/section/AfterQuiz/QuizHistory/module.tsx
  apps/lxp/modules/mytraining-quiz/section/AfterQuiz/QuizHistory/types.d.ts
  apps/lxp/modules/mytraining-quiz/section/AfterQuiz/QuizScore/DetailCard.tsx
  apps/lxp/modules/mytraining-quiz/section/AfterQuiz/QuizScore/NavigationControl.tsx
  apps/lxp/modules/mytraining-quiz/section/AfterQuiz/QuizScore/module.tsx
  apps/lxp/modules/mytraining-quiz/section/AfterQuiz/QuizScore/type.d.ts
  apps/lxp/pages/pelatihanku/quiz/riwayat/[quizID]/[batchID].tsx
  libs/components/atoms/src/button/index.tsx
  libs/utils/src/service/date-time/index.ts
  libs/utils/src/service/index.ts
Labels: enhancement, LXP

#584 feature: kampus gratis dosen
  apps/kg-dosen/.eslintrc.json
  apps/kg-dosen/app/api/hello/route.ts
  apps/kg-dosen/app/global.css
  apps/kg-dosen/app/layout.tsx
  apps/kg-dosen/app/page.tsx
  apps/kg-dosen/index.d.ts
  apps/kg-dosen/jest.config.ts
  apps/kg-dosen/next-env.d.ts
  apps/kg-dosen/next.config.js
  apps/kg-dosen/postcss.config.js
  apps/kg-dosen/project.json
  apps/kg-dosen/public/.gitkeep
  apps/kg-dosen/public/favicon.ico
  apps/kg-dosen/tailwind.config.js
  apps/kg-dosen/tsconfig.json
  apps/kg-dosen/tsconfig.spec.json
  apps/kg-landing-experimental/.eslintrc.json
  apps/kg-landing-experimental/.prettierignore
  apps/kg-landing-experimental/README.md
  apps/kg-landing-experimental/adapters/static/vite.config.ts
  apps/kg-landing-experimental/package.json
  apps/kg-landing-experimental/project.json
  apps/kg-landing-experimental/public/favicon.svg
  apps/kg-landing-experimental/public/manifest.json
  apps/kg-landing-experimental/src/entry.dev.tsx
  apps/kg-landing-experimental/src/entry.preview.tsx
  apps/kg-landing-experimental/src/entry.ssr.tsx
  apps/kg-landing-experimental/src/global.css
  apps/kg-landing-experimental/src/root.tsx
  apps/kg-landing-experimental/src/routes/index.tsx
  apps/kg-landing-experimental/src/routes/layout.tsx
  apps/kg-landing-experimental/src/routes/service-worker.ts
  apps/kg-landing-experimental/tailwind.config.js
  apps/kg-landing-experimental/tsconfig.app.json
  apps/kg-landing-experimental/tsconfig.json
  apps/kg-landing-experimental/vite.config.ts
Labels: enhancement, question, KG

#586 Improvement : integration expandable table request process by id
  apps/cs/src/modules/request/api.ts
  apps/cs/src/modules/request/hooks.ts
  apps/cs/src/modules/request/result/index.tsx
  apps/cs/src/modules/request/result/table.tsx
  apps/cs/src/modules/request/store.ts
  apps/cs/src/modules/request/types.d.ts
Labels: documentation, CS, automerge

#589 improvement : add props checkinput all to component DataTable
  apps/cs/src/modules/report/report-request/table.tsx
  apps/cs/src/modules/report/report-user/table.tsx
  apps/cs/src/modules/request/result/table.tsx
  apps/cs/src/modules/request/types.d.ts
Labels: bug, documentation, CS, automerge

#595 improvement: sidebar, baselayout, and on progress slicing permintaan kuota page
  apps/cs-admin/public/assets/download-bottom.webp
  apps/cs-admin/public/assets/error.png
  apps/cs-admin/public/assets/loader.png
  apps/cs-admin/src/components/organisms/sidebar/index.tsx
  apps/cs-admin/src/components/organisms/sidebar/sidebar-skeleton.tsx
  apps/cs-admin/src/layout/auth/auth.tsx
  apps/cs-admin/src/layout/base/index.tsx
  apps/cs-admin/src/modules/auth/login/index.tsx
  apps/cs-admin/src/modules/common/errorpage.tsx
  apps/cs-admin/src/modules/common/hooks.ts
  apps/cs-admin/src/modules/common/suspense-error.tsx
  apps/cs-admin/src/modules/common/types.d.ts
  apps/cs-admin/src/modules/quota-request/index.tsx
  apps/cs-admin/src/pages/auth/login.tsx
  apps/cs-admin/src/pages/request-quota/index.tsx
  apps/cs-admin/src/routers/index.tsx
  apps/cs-admin/tailwind.config.js
  apps/cs/public/assets/checked.webp
  apps/cs/src/modules/quota/alocation-quota.tsx
  apps/cs/src/modules/request/index.tsx
  apps/cs/src/modules/request/process/index.tsx
  apps/cs/src/modules/request/result/table.tsx
  apps/cs/src/modules/request/types.d.ts
  libs/components/atoms/src/cs/icons/ic-grafic.tsx
  libs/components/atoms/src/cs/icons/ic-quota-admin.tsx
  libs/components/atoms/src/cs/icons/index.ts
  package.json
  yarn.lock
Labels: CS

#605 feature: integrasi dashboard
  .dockerignore
  Dockerfile
  apps/lxp/modules/dashboard/api.ts
  apps/lxp/modules/dashboard/hook.ts
  apps/lxp/modules/dashboard/module.tsx
  apps/lxp/modules/dashboard/resume/section.tsx
  apps/lxp/modules/dashboard/resume/types.ts
  apps/lxp/modules/dashboard/task/section.tsx
  apps/lxp/modules/dashboard/types.ts
  fly.toml
  yarn.lock
Labels: LXP, Critical

#606 fix : navbar aligment and dashboard integration
  apps/lxp/modules/analytic/const.ts
  apps/lxp/modules/career-consulting/const.ts
  apps/lxp/modules/common/provider/ClientProvider/const.ts
  apps/lxp/modules/common/provider/ClientProvider/provider.tsx
  apps/lxp/modules/consulting-service/const.ts
  apps/lxp/modules/dashboard/article/carousel/dummy-assets/dummy-article.svg
  apps/lxp/modules/dashboard/article/carousel/section.tsx
  apps/lxp/modules/dashboard/event/dummy-assets/dummy-event.svg
  apps/lxp/modules/dashboard/event/section.tsx
  apps/lxp/modules/dashboard/module.tsx
  apps/lxp/modules/dashboard/progress/card/dummy-assets/dummy-progress.svg
  apps/lxp/modules/dashboard/progress/card/section.tsx
  apps/lxp/modules/dashboard/progress/card/types.d.ts
  apps/lxp/modules/dashboard/progress/section.tsx
  apps/lxp/modules/dashboard/progress/types.d.ts
  apps/lxp/modules/dashboard/resume/section.tsx
  apps/lxp/modules/dashboard/resume/types.ts
  apps/lxp/modules/dashboard/task/dummy-assets/dummy-task.svg
  apps/lxp/modules/dashboard/task/section.tsx
  apps/lxp/modules/dashboard/task/types.d.ts
  apps/lxp/modules/training-information/const.ts
  apps/lxp/modules/training-plan/const.tsx
  libs/components/molecules/src/navbar/section/top-nav/dropdown-menu/user.tsx
Labels: bug, LXP, Critical

#597 improvement: hasil analisis
  apps/kg/modules/analytic/module.tsx
  apps/kg/modules/assignment/module.tsx
  apps/kg/modules/career-planing/assets/checked.svg
  apps/kg/modules/career-planing/assets/logo-adobe.svg
  apps/kg/modules/career-planing/assets/logo-figma.svg
  apps/kg/modules/career-planing/assets/logo-framer.svg
  apps/kg/modules/career-planing/career-planing/index.ts
  apps/kg/modules/career-planing/career-planing/landing.tsx
  apps/kg/modules/career-planing/career-planing/module.tsx
  apps/kg/modules/career-planing/const.ts
  apps/kg/modules/career-planing/hasil-analisa/hasil.tsx
  apps/kg/modules/career-planing/hasil-analisa/index.ts
  apps/kg/modules/career-planing/hasil-analisa/module.tsx
  apps/kg/modules/career-planing/hasil-analisa/recent.tsx
  apps/kg/modules/career-planing/index.ts
  apps/kg/modules/leaderboard/module.tsx
  apps/kg/pages/perencanaan-karir/hasil-analisa/index.tsx
  apps/kg/pages/perencanaan-karir/index.tsx
  apps/kg/tailwind.config.js
Labels: enhancement, KG

#614 bug fixing, create and integrate my-training assigment
  apps/lxp/modules/consulting-service/product/product.tsx
  apps/lxp/modules/guide-guide book/const.ts
  apps/lxp/modules/guide-guide book/section/hero/hero.tsx
  apps/lxp/modules/guide-guide dictinoary/section/content.tsx
  apps/lxp/modules/guide-guide dictinoary/section/sidebar.tsx
  apps/lxp/modules/guide-guide video home/assets/panduan-hero.svg
  apps/lxp/modules/guide-guide video home/section/hero/hero.tsx
  apps/lxp/modules/guide/store.ts
  apps/lxp/modules/my-training-assigment/api.ts
  apps/lxp/modules/my-training-assigment/assets/pdf.svg
  apps/lxp/modules/my-training-assigment/hooks.ts
  apps/lxp/modules/my-training-assigment/index.tsx
  apps/lxp/modules/my-training-assigment/stores.ts
  apps/lxp/modules/my-training-assigment/type.d.ts
  apps/lxp/modules/my-training-video-module/section/ContentSection.tsx
  apps/lxp/modules/mytraining-course/content/section.tsx
  apps/lxp/pages/_app.tsx
  apps/lxp/pages/pelatihanku/penugasan/index.tsx
Labels: bug, enhancement, LXP

#626 bug fix : administrasi, rencana pelatihan, dashboard, otp input
  apps/lxp/modules/administrations/common/PrivatInformationAccordion.tsx
  apps/lxp/modules/auth/otp/module.tsx
  apps/lxp/modules/common/empty-state/index.ts
  apps/lxp/modules/common/empty-state/module.tsx
  apps/lxp/modules/common/empty-state/types.d.ts
  apps/lxp/modules/common/not-found/types.d.ts
  apps/lxp/modules/dashboard/event/dummy-assets/emptyEvent.svg
  apps/lxp/modules/dashboard/event/section.tsx
  apps/lxp/modules/dashboard/module.tsx
  apps/lxp/modules/dashboard/progress/card/section.tsx
  apps/lxp/modules/dashboard/resume/section.tsx
  apps/lxp/modules/dashboard/task/dummy-assets/emptyTask.svg
  apps/lxp/modules/dashboard/task/section.tsx
  apps/lxp/modules/training-plan/hook.ts
  apps/lxp/modules/training-plan/training-plan.tsx
  libs/components/molecules/src/navbar/section/top-nav/dropdown-menu/user.tsx
Labels: bug, enhancement, LXP, Critical

#633 Feature : slicing quota chart card section
  apps/cs-admin/public/assets/chart-quota/asset1.svg
  apps/cs-admin/public/assets/chart-quota/asset2.svg
  apps/cs-admin/public/assets/chart-quota/asset3.svg
  apps/cs-admin/src/components/moleculs/chart/bar-chart.jsx
  apps/cs-admin/src/components/organisms/sidebar/index.tsx
  apps/cs-admin/src/modules/auth/login/index.tsx
  apps/cs-admin/src/modules/chart-quota/index.tsx
  apps/cs-admin/src/pages/chart-quota/index.tsx
  apps/cs-admin/src/routers/index.tsx
  apps/cs/src/modules/auth/login/index.tsx
  apps/cs/src/modules/home/history-request-section.tsx
  apps/cs/src/modules/quota/alocation-quota.tsx
  apps/cs/src/modules/quota/api.ts
  apps/cs/src/modules/quota/types.ts
  libs/components/molecules/src/card-cs/index.tsx
Labels: documentation, CS, automerge

#635 replace href to dashboard
  apps/lxp/modules/administrations/constant.ts
  apps/lxp/modules/assigment/constant.ts
  apps/lxp/modules/assigment/module.tsx
  apps/lxp/modules/guide-guide book/const.ts
  apps/lxp/modules/guide-guide book/module.tsx
  apps/lxp/modules/guide-guide dictinoary detail/constant.ts
  apps/lxp/modules/guide-guide dictinoary detail/module.tsx
  apps/lxp/modules/guide-guide dictinoary/constant.ts
  apps/lxp/modules/guide-guide dictinoary/module.tsx
  apps/lxp/modules/guide-guide video home/const.ts
  apps/lxp/modules/guide-guide video home/module.tsx
  apps/lxp/modules/guide-guide video/const.ts
  apps/lxp/modules/guide-guide video/module.tsx
  apps/lxp/modules/guide/const.ts
  apps/lxp/modules/guide/module.tsx
  apps/lxp/modules/guide/section/hero/hero.tsx
  apps/lxp/modules/my-training/assets/dataKosong.svg
  apps/lxp/modules/my-training/constant.tsx
  apps/lxp/modules/my-training/section/ContentSection.tsx
  apps/lxp/modules/mytraining-course/const.ts
  apps/lxp/modules/mytraining-module/const.ts
  apps/lxp/modules/mytraining-quiz/const.tsx
  apps/lxp/modules/profile/const.ts
  apps/lxp/modules/score-sertificate/const.ts
  apps/lxp/modules/unique-event/const.tsx
Labels: bug, LXP, Critical

#636 improvement : dashboard empty card and event tab
  apps/lxp/modules/common/empty-state/module.tsx
  apps/lxp/modules/dashboard/event/dummy-assets/emptyEvent.svg
  apps/lxp/modules/dashboard/event/section.tsx
  apps/lxp/modules/dashboard/progress/assets/empty-progress.svg
  apps/lxp/modules/dashboard/progress/card/section.tsx
  apps/lxp/modules/dashboard/progress/section.tsx
  apps/lxp/modules/dashboard/resume/section.tsx
  apps/lxp/modules/dashboard/task/dummy-assets/emptyTask.svg
  apps/lxp/modules/dashboard/task/section.tsx
  apps/lxp/modules/unique-event/UniqueEventModule.tsx
  apps/lxp/modules/unique-event/event-sidebar/options/UniqueSidebarOptions.tsx
  apps/lxp/pages/acara-unik/[slug]/index.tsx
  apps/lxp/pages/event-pelatihan/detail/[slug].tsx
  apps/lxp/pages/event-pelatihan/index.tsx
Labels: bug, LXP

#637 improvement: integration webinar and matakuliah certificate
  apps/kg/modules/score-sertificate/api.ts
  apps/kg/modules/score-sertificate/section/certificate/certificate.tsx
  apps/kg/modules/score-sertificate/type.d.ts
  apps/kg/tailwind.config.js
Labels: enhancement, KG

#638 Improvement: Slicing Filter Modal and History Quota Request tab CS-Admin
  apps/cs-admin/src/modules/quota-request/api.ts
  apps/cs-admin/src/modules/quota-request/hooks.ts
  apps/cs-admin/src/modules/quota-request/index.tsx
  apps/cs-admin/src/modules/quota-request/request-history/index.tsx
  apps/cs-admin/src/modules/quota-request/request-history/table.tsx
  apps/cs-admin/src/modules/quota-request/request-quota/index.tsx
  apps/cs-admin/src/modules/quota-request/request-quota/table.tsx
  apps/cs-admin/src/modules/quota-request/store.ts
  apps/cs-admin/src/modules/quota-request/types.d.ts
  apps/cs-admin/src/services/api.ts
  apps/cs-admin/src/services/token.ts
  apps/cs-admin/tailwind.config.js
  libs/components/atoms/src/cs/icons/ic-arrow.tsx
  libs/components/atoms/src/cs/icons/ic-clock.tsx
  libs/components/atoms/src/cs/icons/ic-close.tsx
  libs/components/atoms/src/cs/icons/ic-filter.tsx
  libs/components/atoms/src/cs/icons/ic-warning.tsx
  libs/components/atoms/src/cs/icons/index.ts
  libs/components/molecules/src/date_range_picker/index.tsx
Labels: CS

#639 feature: integration progress dicsussion-global kg
  apps/kg/modules/discussion-room/content/post/modal/delete-comfirm/api.ts
  apps/kg/modules/discussion-room/content/post/modal/delete-comfirm/hooks.ts
  apps/kg/modules/discussion-room/content/post/modal/delete-comfirm/section.tsx
  apps/kg/modules/discussion-room/content/post/modal/delete-comfirm/types.d.ts
  apps/kg/modules/discussion-room/content/post/modal/post-create/section.tsx
  apps/kg/modules/discussion-room/content/post/modal/post-edit/api.ts
  apps/kg/modules/discussion-room/content/post/modal/post-edit/hooks.ts
  apps/kg/modules/discussion-room/content/post/modal/post-edit/section.tsx
  apps/kg/modules/discussion-room/content/post/option/section.tsx
Labels: enhancement, KG

#646 bugfix : pelatihanku style and view profile integration
  apps/lxp/modules/dashboard/progress/section.tsx
  apps/lxp/modules/my-training/module.tsx
  apps/lxp/modules/my-training/section/ContentSection.tsx
  apps/lxp/modules/my-training/section/HeroSection.tsx
  apps/lxp/modules/profile/main/view-profile/hero/sectioin.tsx
  apps/lxp/modules/profile/main/view-profile/hero/type.d.ts
  apps/lxp/modules/profile/main/view-profile/info/section.tsx
  apps/lxp/modules/profile/main/view-profile/info/types.d.ts
  apps/lxp/modules/profile/main/view-profile/section.tsx
  apps/lxp/modules/profile/main/view-profile/types.d.ts
  apps/lxp/modules/profile/module.tsx
  apps/lxp/modules/profile/types.d.ts
  apps/lxp/modules/training-plan/training-plan.tsx
  libs/components/molecules/src/navbar/section/top-nav/dropdown-menu/user.tsx
Labels: bug, enhancement

#649 Bugfix : lxp profile fetching error cause by change from BE response
  apps/lxp/modules/common/provider/ClientProvider/provider.tsx
  apps/lxp/modules/profile/main/edit-profile/section.tsx
  apps/lxp/modules/profile/main/view-profile/hero/sectioin.tsx
  apps/lxp/modules/profile/main/view-profile/info/section.tsx
  apps/lxp/modules/profile/main/view-profile/info/types.d.ts
  apps/lxp/modules/profile/main/view-profile/section.tsx
  apps/lxp/modules/profile/main/view-profile/stats/section.tsx
  apps/lxp/modules/profile/main/view-profile/stats/types.d.ts
  apps/lxp/modules/profile/main/view-profile/types.d.ts
  apps/lxp/modules/profile/module.tsx
  apps/lxp/modules/profile/types.d.ts
Labels: bug, Critical

#653 improvement : integration auth cs admin
  apps/cs-admin/src/layout/auth/auth.tsx
  apps/cs-admin/src/modules/auth/login/api.ts
  apps/cs-admin/src/modules/auth/login/hooks.ts
  apps/cs-admin/src/modules/auth/login/index.tsx
  apps/cs-admin/src/modules/auth/login/types.d.ts
  apps/cs-admin/src/modules/auth/middleware/guest.tsx
  apps/cs-admin/src/modules/auth/middleware/index.ts
  apps/cs-admin/src/modules/auth/middleware/protected.tsx
Labels: documentation, CS, automerge

#645 fix bg color breadcrumb guide
  apps/lxp/modules/guide-guide book/module.tsx
  apps/lxp/modules/guide-guide dictinoary detail/module.tsx
  apps/lxp/modules/guide-guide dictinoary/module.tsx
  apps/lxp/modules/guide-guide video home/module.tsx
  apps/lxp/modules/guide-guide video/module.tsx
  apps/lxp/modules/guide/module.tsx
  apps/lxp/modules/my-training-discussion/common/cardAuthor.tsx
  apps/lxp/modules/my-training-discussion/constant.tsx
  apps/lxp/modules/my-training-discussion/module.tsx
  apps/lxp/modules/my-training-discussion/section/content.tsx
  apps/lxp/modules/my-training-video-module/module.tsx
  apps/lxp/modules/mytraining-course/const.tsx
  apps/lxp/modules/mytraining-course/module.tsx
  apps/lxp/modules/mytraining-module/const.ts
  apps/lxp/modules/mytraining-module/module.tsx
  apps/lxp/modules/mytraining-quiz/const.tsx
  apps/lxp/modules/mytraining-quiz/section/AfterQuiz/QuizHistory/module.tsx
Labels: bug, LXP

#661 improvment : lxp profile integration and uploaded image preview
  apps/lxp/modules/profile/main/edit-profile/api.ts
  apps/lxp/modules/profile/main/edit-profile/hook.ts
  apps/lxp/modules/profile/main/edit-profile/section.tsx
  apps/lxp/modules/profile/main/edit-profile/types.d.ts
  libs/utils/src/service/image-preview/index.ts
  libs/utils/src/service/index.ts
Labels: bug, enhancement, LXP

#647 feature : base layout
  apps/lxp-admin/components/base/index.tsx
  apps/lxp-admin/components/base/sidebar/type.d.ts
  apps/lxp-admin/components/base/type.d.ts
  apps/lxp-admin/modules/dashboard/InfoSection.tsx
  apps/lxp-admin/modules/dashboard/assets/karyawan.svg
  apps/lxp-admin/modules/dashboard/assets/pendaftar.svg
  apps/lxp-admin/modules/dashboard/index.tsx
  apps/lxp-admin/tailwind.config.js
  libs/components/molecules/src/admin-sidebar/index.tsx
  libs/components/molecules/src/admin-sidebar/sidebar.tsx
  libs/components/molecules/src/admin-sidebar/type.d.ts
  libs/components/molecules/src/index.ts
Labels: enhancement

#668 feature: adashboard
  apps/lxp-admin/components/base/index.tsx
  apps/lxp-admin/modules/dashboard/GrafikSection.tsx
  apps/lxp-admin/modules/dashboard/InfoSection.tsx
  apps/lxp-admin/modules/dashboard/PelatihanSection.tsx
  apps/lxp-admin/modules/dashboard/index.tsx
  libs/components/molecules/src/admin-sidebar/index.tsx
  libs/components/molecules/src/admin-sidebar/type.d.ts
Labels: enhancement

#667 feature : dashboard integration
  apps/kg/modules/dashboard/api.ts
  apps/kg/modules/dashboard/content/calendar/hooks.ts
  apps/kg/modules/dashboard/content/calendar/section.tsx
  apps/kg/modules/dashboard/content/calendar/store.ts
  apps/kg/modules/dashboard/content/calendar/types.d.ts
  apps/kg/modules/dashboard/content/progress/progress.module.css
  apps/kg/modules/dashboard/content/progress/section.tsx
  apps/kg/modules/dashboard/content/task-event/event/section.tsx
  apps/kg/modules/dashboard/content/task-event/task/section.tsx
  apps/kg/modules/dashboard/hooks.ts
  apps/kg/modules/dashboard/module.tsx
  apps/kg/modules/dashboard/sidebar/article/section.tsx
  apps/kg/modules/dashboard/sidebar/leaderboard/ever-done/ever-done.tsx
  apps/kg/modules/dashboard/sidebar/leaderboard/ever-done/index.ts
  apps/kg/modules/dashboard/sidebar/leaderboard/index.ts
  apps/kg/modules/dashboard/sidebar/leaderboard/leaderboard.tsx
  apps/kg/modules/dashboard/sidebar/leaderboard/never-done/index.ts
  apps/kg/modules/dashboard/sidebar/leaderboard/never-done/never-done.tsx
  apps/kg/modules/dashboard/sidebar/leaderboard/section.tsx
  apps/kg/modules/dashboard/sidebar/resume/const.ts
  apps/kg/modules/dashboard/sidebar/resume/index.ts
  apps/kg/modules/dashboard/sidebar/resume/resume.tsx
  apps/kg/modules/dashboard/sidebar/resume/section.tsx
  apps/kg/modules/dashboard/store.ts
  apps/kg/modules/dashboard/types.d.ts
Labels: enhancement, KG

#673 Improvement : fix integration cs
  apps/cs/src/modules/report/api.ts
  apps/cs/src/modules/report/hooks.ts
  apps/cs/src/modules/report/report-request/table.tsx
  apps/cs/src/modules/report/report-user/table.tsx
  apps/cs/src/modules/report/store.ts
  apps/cs/src/modules/report/type.d.ts
  apps/cs/src/modules/report/types.ts
  apps/cs/src/modules/request/feature/request.tsx
  apps/cs/src/modules/request/types.d.ts
  apps/cs/src/modules/user/table.tsx
  apps/cs/src/modules/user/types.d.ts
  apps/cs/src/modules/user/types.ts
  apps/cs/tsconfig.spec.json
  apps/kg-admin/modules/dashboard/index.tsx
  libs/components/atoms/src/cs/index.ts
  libs/components/molecules/src/admin-sidebar/index.tsx
  libs/components/molecules/src/admin-sidebar/type.d.ts
  libs/components/molecules/src/index.ts
  libs/components/molecules/src/pagination/index.tsx
  libs/components/molecules/src/sidebar/index.tsx
Labels: CS

#679 Improvement : integration expand table on report page
  apps/cs/src/modules/report/hooks.ts
  apps/cs/src/modules/report/index.tsx
  apps/cs/src/modules/report/report-request/index.tsx
  apps/cs/src/modules/report/report-request/table.tsx
  apps/cs/src/modules/report/report-user/index.tsx
  apps/cs/src/modules/report/report-user/table.tsx
  apps/cs/src/modules/report/types.ts
  apps/cs/src/modules/request/process/table.tsx
  apps/cs/src/modules/user/index.tsx
  libs/components/molecules/src/index.ts
  libs/components/molecules/src/pagination/index.tsx
Labels: documentation, CS, automerge

#680 Improvement : integration choice feature request page
  apps/cs/src/modules/request/check-result/index.tsx
  apps/cs/src/modules/request/feature/choice-feature/table.tsx
  apps/cs/src/modules/request/feature/request.tsx
  apps/cs/src/modules/request/result/table.tsx
  apps/cs/src/routers/index.tsx
Labels: documentation

#696 improvement: drill simulation, leaderboard, guide, administration
  apps/kg/modules/administration/file-information/index.tsx
  apps/kg/modules/administration/jobs-information/index.tsx
  apps/kg/modules/administration/private-information/index.tsx
  apps/kg/modules/drill-simulasi/assets/dummy-success.svg
  apps/kg/modules/drill-simulasi/section/content/simulasion/history.tsx
  apps/kg/modules/drill-simulasi/section/content/simulasion/submisson.tsx
  apps/kg/modules/drill-simulasi/section/reschedule/section/content.tsx
  apps/kg/modules/drill-simulasi/section/reschedule/section/dateTime.tsx
  apps/kg/modules/drill-simulasi/type.d.ts
  apps/kg/modules/guide/guide-book/hero/hero.tsx
  apps/kg/modules/guide/guide-dictionary-detail/content/content.tsx
  apps/kg/modules/guide/guide-dictionary-detail/sidebar/sidebar.tsx
  apps/kg/modules/guide/guide-dictionary/content/content.tsx
  apps/kg/modules/guide/guide-dictionary/sidebar/sidebar.tsx
  apps/kg/modules/guide/guide-video/hero/hero.tsx
  apps/kg/modules/guide/landing/faq/faq.tsx
  apps/kg/modules/guide/landing/guide/guide.tsx
  apps/kg/modules/guide/landing/hero/hero.tsx
  apps/kg/modules/guide/registration-book/hero/hero.tsx
  apps/kg/modules/guide/registration-video/const.ts
  apps/kg/modules/guide/registration-video/description/description.tsx
  apps/kg/modules/leaderboard/components/popup-profil.tsx
  apps/kg/modules/leaderboard/components/type.d.ts
  apps/kg/modules/leaderboard/section/filter.tsx
  apps/kg/modules/leaderboard/section/module.tsx
  apps/kg/modules/leaderboard/section/ranking-bottom.tsx
  apps/kg/modules/leaderboard/section/ranking-up.tsx
  apps/kg/modules/leaderboard/store.ts
  apps/kg/modules/leaderboard/type.d.ts
  apps/kg/tailwind.config.js
Labels: enhancement, KG
