Repository magang-mknows/mknows-fe, pull requests merged in 2023-05, with the labels that each got.

#18 Master
  apps/kg/modules/mystudy/subject/api.ts
  apps/kg/modules/mystudy/subject/types.d.ts
  apps/kg/pages/api/subject/index.ts
Labels: enhancement

#24 improvement: add get integration (KG)
  apps/kg/.env
  apps/kg/modules/administration/api.ts
  apps/kg/modules/administration/type.d.ts
  apps/kg/modules/assignment/api.ts
  apps/kg/modules/assignment/types.d.ts
  apps/kg/pages/api/studi-ku/assignment/session/[session_id]/index.ts
Labels: enhancement

#27 improvement: integration get all faculty
  apps/kg/modules/study-plan/api.ts
  apps/kg/modules/study-plan/types.d.ts
  apps/kg/pages/api/faculty/index.ts
Labels: enhancement

#29 improvement: add layout banner assignment
  apps/kg/modules/assignment/hooks.ts
  apps/kg/modules/assignment/index.ts
  apps/kg/modules/assignment/module.tsx
  apps/kg/modules/assignment/section/banner/index.ts
  apps/kg/modules/assignment/section/banner/section.tsx
  apps/kg/modules/assignment/section/index.ts
  apps/kg/modules/index.ts
  apps/kg/pages/api/studi-ku/assignment/session/[session_id]/submission.ts
  apps/kg/pages/api/studi-ku/assignment/session/[session_id]/submission/index.ts
  apps/kg/pages/penugasan/index.tsx
Labels: enhancement

#30 feature : calendarSchedule types and mock api (KG)
  apps/kg/modules/dashboard/calendar/api.ts
  apps/kg/modules/dashboard/calendar/types.d.ts
  apps/kg/pages/api/dashboard/calender/index.ts
  apps/kg/pages/api/mystudy/index.ts
Labels: enhancement

#34 improvement: recode ui choicefaculty and studyprogram
  apps/kg/modules/study-plan/ChoiceFaculty.tsx
  apps/kg/modules/study-plan/StudyProgram.tsx
  apps/kg/modules/study-plan/assets/DataKosong.png
  apps/kg/modules/study-plan/assets/search.svg
  apps/kg/modules/study-plan/components/Card.tsx
  apps/kg/modules/study-plan/components/types.d.ts
  apps/kg/modules/study-plan/hooks.ts
  apps/kg/modules/study-plan/stores.ts
  apps/kg/modules/study-plan/types.d.ts
Labels: enhancement

#33 Improvement: add layout content in assigment
  apps/kg/modules/assignment/assets/assigned-assesment.svg
  apps/kg/modules/assignment/assets/assigned-assigment.svg
  apps/kg/modules/assignment/assets/assigned-done.svg
  apps/kg/modules/assignment/assets/assigned-late.svg
  apps/kg/modules/assignment/assets/data-null.svg
  apps/kg/modules/assignment/component/assignment-card.tsx
  apps/kg/modules/assignment/component/type.d.ts
  apps/kg/modules/assignment/module.tsx
  apps/kg/modules/assignment/section/content/content.tsx
  apps/kg/modules/assignment/section/content/hooks.ts
  apps/kg/modules/assignment/section/content/index.ts
  apps/kg/modules/assignment/section/content/store.ts
  apps/kg/modules/assignment/section/content/types.d.ts
  apps/kg/modules/assignment/section/index.ts
  apps/kg/modules/assignment/types.d.ts
Labels: enhancement

#36 feature : dashboard UI
  apps/kg/modules/dashboard/assets/LihatSemua.svg
  apps/kg/modules/dashboard/assets/acara.svg
  apps/kg/modules/dashboard/assets/article-slide.svg
  apps/kg/modules/dashboard/assets/bigTrophyIcon.svg
  apps/kg/modules/dashboard/assets/clockIcon.svg
  apps/kg/modules/dashboard/assets/dummyCourse.png
  apps/kg/modules/dashboard/assets/emptyLeaderBoard.svg
  apps/kg/modules/dashboard/assets/emptyTask.svg
  apps/kg/modules/dashboard/assets/homeIcon.svg
  apps/kg/modules/dashboard/assets/labIcon.svg
  apps/kg/modules/dashboard/assets/medal1Icon.svg
  apps/kg/modules/dashboard/assets/medal2Icon.svg
  apps/kg/modules/dashboard/assets/medal3Icon.svg
  apps/kg/modules/dashboard/assets/penugasan.svg
  apps/kg/modules/dashboard/assets/trophyIcon.svg
  apps/kg/modules/dashboard/content/calendar/api.ts
  apps/kg/modules/dashboard/content/calendar/index.ts
  apps/kg/modules/dashboard/content/calendar/section.tsx
  apps/kg/modules/dashboard/content/calendar/store.ts
  apps/kg/modules/dashboard/content/calendar/types.d.ts
  apps/kg/modules/dashboard/content/index.ts
  apps/kg/modules/dashboard/content/progress/hooks.ts
  apps/kg/modules/dashboard/content/progress/index.ts
  apps/kg/modules/dashboard/content/progress/section.tsx
  apps/kg/modules/dashboard/content/progress/store.ts
  apps/kg/modules/dashboard/content/progress/types.d.ts
  apps/kg/modules/dashboard/content/section.tsx
  apps/kg/modules/dashboard/content/task-event/event/hooks.ts
  apps/kg/modules/dashboard/content/task-event/event/index.ts
  apps/kg/modules/dashboard/content/task-event/event/section.tsx
  apps/kg/modules/dashboard/content/task-event/event/store.ts
  apps/kg/modules/dashboard/content/task-event/event/types.d.ts
  apps/kg/modules/dashboard/content/task-event/task/hooks.ts
  apps/kg/modules/dashboard/content/task-event/task/index.ts
  apps/kg/modules/dashboard/content/task-event/task/section.tsx
  apps/kg/modules/dashboard/content/task-event/task/store.ts
  apps/kg/modules/dashboard/content/task-event/task/types.d.ts
  apps/kg/modules/dashboard/index.ts
  apps/kg/modules/dashboard/module.tsx
  apps/kg/modules/dashboard/sidebar/article/index.ts
  apps/kg/modules/dashboard/sidebar/article/section.tsx
  apps/kg/modules/dashboard/sidebar/article/store.ts
  apps/kg/modules/dashboard/sidebar/index.ts
  apps/kg/modules/dashboard/sidebar/leaderboard/index.ts
  apps/kg/modules/dashboard/sidebar/leaderboard/section.tsx
  apps/kg/modules/dashboard/sidebar/leaderboard/store.ts
  apps/kg/modules/dashboard/sidebar/resume/index.ts
  apps/kg/modules/dashboard/sidebar/resume/section.tsx
  apps/kg/modules/dashboard/sidebar/resume/store.ts
  apps/kg/modules/dashboard/sidebar/section.tsx
  apps/kg/pages/_app.tsx
  apps/kg/pages/dashboard/index.tsx
  apps/kg/pages/styles.css
Labels: enhancement

#43 improvement: recode ui submission contract study
  apps/kg/modules/study-plan/ChoiceFaculty.tsx
  apps/kg/modules/study-plan/StudyProgram.tsx
  apps/kg/modules/study-plan/SubmissionContractStudy.tsx
  apps/kg/modules/study-plan/assets/confirm.svg
  apps/kg/modules/study-plan/assets/data-kosong.png
  apps/kg/modules/study-plan/assets/download.svg
  apps/kg/modules/study-plan/assets/warning.svg
  apps/kg/modules/study-plan/components/Modal.tsx
  apps/kg/modules/study-plan/components/PopupModal.tsx
  apps/kg/modules/study-plan/hooks.ts
  apps/kg/modules/study-plan/stores.ts
Labels: enhancement

#80 feature: create hooks, api, and types profile
  apps/kg/modules/profile/api.ts
  apps/kg/modules/profile/hooks.ts
  apps/kg/modules/profile/types.d.ts
Labels: enhancement

#82 feature: progress recode ui profile
  apps/kg/modules/profile/EditProfileSection.tsx
Labels: enhancement

#86 improvement: migrasi ui
  apps/kg/modules/study-plan/assets/choicefaculty2.svg
  apps/kg/modules/study-plan/assets/example1.svg
  apps/kg/modules/study-plan/assets/example2.svg
  apps/kg/modules/study-plan/stores.ts
  apps/kg/pages/rencana-studi/index.tsx
Labels: enhancement

#90 migration credit scoring
  apps/cs-vite/src/components/molecules/input/date-input/index.tsx
  apps/cs-vite/src/main.tsx
  apps/cs-vite/src/modules/auth/login/index.tsx
  apps/cs-vite/src/modules/home/history-request-section.tsx
  apps/cs-vite/src/modules/home/index.tsx
  apps/cs-vite/src/modules/quota/alocation-quota.tsx
  apps/cs-vite/src/modules/quota/history-alocation.tsx
  apps/cs-vite/src/modules/quota/index.tsx
  apps/cs-vite/src/modules/quota/table.tsx
  apps/cs-vite/src/modules/report/grafik/index.tsx
  apps/cs-vite/src/modules/report/loading.tsx
  apps/cs-vite/src/modules/report/report.tsx
  apps/cs-vite/src/modules/report/table.tsx
  apps/cs-vite/src/modules/request/index.tsx
  apps/cs-vite/src/modules/request/loading.tsx
  apps/cs-vite/src/modules/request/process.tsx
  apps/cs-vite/src/modules/request/request.tsx
  apps/cs-vite/src/modules/request/result.tsx
  apps/cs-vite/src/modules/request/table.tsx
  apps/cs-vite/src/modules/user/index.tsx
  apps/cs-vite/src/modules/user/table.tsx
  apps/cs-vite/src/pages/home/index.tsx
  apps/cs-vite/src/pages/quota/index.tsx
  apps/cs-vite/src/pages/report/index.tsx
  apps/cs-vite/src/pages/request/index.tsx
  apps/cs-vite/src/pages/user/add-data.tsx
  apps/cs-vite/src/pages/user/index.tsx
  apps/cs-vite/src/routers/index.tsx
Labels: enhancement

#106 feature: finish recode ui profile
  apps/kg/middleware.ts
  apps/kg/modules/index.ts
  apps/kg/modules/profile/index.ts
  apps/kg/modules/profile/module.tsx
  apps/kg/modules/profile/section/EditProfile.tsx
  apps/kg/modules/profile/section/ResetPasswordSection.tsx
  apps/kg/pages/profile/index.tsx
Labels: enhancement

#108 feature : add tailwind to project vite credit scoring
  apps/cs-vite/src/components/atoms/icons/ic-quota.tsx
  apps/cs-vite/src/main.tsx
  apps/cs-vite/src/modules/home/history-request-section.tsx
Labels: enhancement

#110 improvement: change color and text
  apps/kg/modules/assignment/component/assignment-card.tsx
  apps/kg/modules/assignment/section/content/content.tsx
Labels: enhancement

#115 feature: fix ui edit profile and reset password
  apps/kg/modules/common/layout/base/section.tsx
  apps/kg/modules/profile/assets/camera-ojan.webp
  apps/kg/modules/profile/assets/cewe-cantik.webp
  apps/kg/modules/profile/index.ts
  apps/kg/modules/profile/module.tsx
  apps/kg/modules/profile/section/edit-profile/EditProfile.tsx
  apps/kg/modules/profile/section/edit-profile/api.ts
  apps/kg/modules/profile/section/edit-profile/hooks.ts
  apps/kg/modules/profile/section/edit-profile/index.ts
  apps/kg/modules/profile/section/edit-profile/types.d.ts
  apps/kg/modules/profile/section/index.ts
  apps/kg/modules/profile/section/reset-password/ResetPassword.tsx
  apps/kg/modules/profile/section/reset-password/index.ts
  apps/kg/pages/profile/index.tsx
  apps/kg/pages/profile/reset-password/index.tsx
Labels: enhancement

#116 Origin/feature/kg/migrate UI card and studi ku
  apps/kg/modules/mystudy/hooks.ts
  apps/kg/modules/mystudy/index.tsx
  apps/kg/modules/mystudy/store.ts
  apps/kg/modules/mystudy/typed.d.ts
  apps/kg/modules/study-plan/StudyProgram.tsx
  apps/kg/pages/rencana-studi/fakultas/[...slug].tsx
  apps/kg/pages/rencana-studi/index.tsx
  libs/components/molecules/src/card/index.tsx
  libs/components/molecules/src/card/types.d.ts
Labels: enhancement

#117 feature: migration drill simulation
  apps/kg/middleware.ts
  apps/kg/modules/drill-simulasi/assets/assigned-done.svg
  apps/kg/modules/drill-simulasi/assets/dummy-drill.svg
  apps/kg/modules/drill-simulasi/assets/dummy-drillHistory.svg
  apps/kg/modules/drill-simulasi/assets/popup-modal-jadwal.svg
  apps/kg/modules/drill-simulasi/assets/search.svg
  apps/kg/modules/drill-simulasi/assets/simualasi-null.svg
  apps/kg/modules/drill-simulasi/assets/simulasi-checked.svg
  apps/kg/modules/drill-simulasi/assets/simulasi-done.svg
  apps/kg/modules/drill-simulasi/assets/vector-popup-modal-loading.svg
  apps/kg/modules/drill-simulasi/index.tsx
  apps/kg/modules/drill-simulasi/module.tsx
  apps/kg/modules/drill-simulasi/section/content/content.tsx
  apps/kg/modules/drill-simulasi/section/content/index.tsx
  apps/kg/modules/drill-simulasi/section/hero/hero.tsx
  apps/kg/modules/drill-simulasi/section/hero/index.tsx
  apps/kg/modules/drill-simulasi/section/hero/store.ts
  apps/kg/modules/drill-simulasi/section/hero/type.d.ts
  apps/kg/modules/drill-simulasi/section/index.tsx
  apps/kg/modules/index.ts
  apps/kg/pages/_app.tsx
  apps/kg/pages/simulasi-drill-dan-assestment/index.tsx
Labels: enhancement

#130 Origin/feature/kg/migrate UI card and studi ku
  apps/kg/modules/mystudy/index.tsx
  apps/kg/modules/mystudy/store.ts
  apps/kg/pages/studi-ku/index.tsx
  libs/components/molecules/src/card/component.tsx
  libs/components/molecules/src/card/index.ts
  libs/components/molecules/src/card/index.tsx
  libs/components/molecules/src/card/type.d.ts
  libs/components/molecules/src/card/types.d.ts
  libs/components/molecules/src/index.ts
Labels: enhancement

#129 Improvement/kg/adminsitration biodata
  apps/kg/modules/administration/api.ts
  apps/kg/modules/administration/hooks.ts
  apps/kg/modules/administration/jobs-information/index.tsx
  apps/kg/modules/administration/types.d.ts
Labels: enhancement

#136 feature : quiz home and quiz take UI (KG)
  apps/kg/modules/common/hooks/index.ts
  apps/kg/modules/common/hooks/use-window-size/index.ts
  apps/kg/modules/common/hooks/use-window-size/section.tsx
  apps/kg/modules/common/hooks/use-window-size/types.d.ts
  apps/kg/modules/mystudy/quiz/assets/quiz-home-person.svg
  apps/kg/modules/mystudy/quiz/index.ts
  apps/kg/modules/mystudy/quiz/module.tsx
  apps/kg/modules/mystudy/quiz/take/components/quiz-timer/hooks.ts
  apps/kg/modules/mystudy/quiz/take/components/quiz-timer/index.ts
  apps/kg/modules/mystudy/quiz/take/components/quiz-timer/section.tsx
  apps/kg/modules/mystudy/quiz/take/components/quiz-timer/types.d.ts
  apps/kg/modules/mystudy/quiz/take/hooks.ts
  apps/kg/modules/mystudy/quiz/take/index.ts
  apps/kg/modules/mystudy/quiz/take/module.tsx
  apps/kg/modules/mystudy/quiz/take/store.ts
  apps/kg/modules/mystudy/quiz/take/type.d.ts
  apps/kg/pages/studi-ku/[detail-matkul]/kuis/ambil/index.tsx
  apps/kg/pages/studi-ku/[detail-matkul]/kuis/index.tsx
Labels: enhancement

#142 feature : quiz score and quiz history UI (KG)
  apps/kg/modules/mystudy/quiz/common/components/detail-card/index.ts
  apps/kg/modules/mystudy/quiz/common/components/detail-card/section.tsx
  apps/kg/modules/mystudy/quiz/common/components/detail-card/types.d.ts
  apps/kg/modules/mystudy/quiz/history/components/history-card/index.ts
  apps/kg/modules/mystudy/quiz/history/components/history-card/section.tsx
  apps/kg/modules/mystudy/quiz/history/index.ts
  apps/kg/modules/mystudy/quiz/history/module.tsx
  apps/kg/modules/mystudy/quiz/score/index.ts
  apps/kg/modules/mystudy/quiz/score/module.tsx
  apps/kg/pages/studi-ku/[detail-matkul]/kuis/riwayat/index.tsx
  apps/kg/pages/studi-ku/[detail-matkul]/kuis/skor/index.tsx
Labels: enhancement

#144 Improvement: drill simulation
  apps/kg/modules/assignment/constanta.ts
  apps/kg/modules/assignment/module.tsx
  apps/kg/modules/drill-simulasi/api.ts
  apps/kg/modules/drill-simulasi/constant.ts
  apps/kg/modules/drill-simulasi/hooks.ts
  apps/kg/modules/drill-simulasi/index.ts
  apps/kg/modules/drill-simulasi/module.tsx
  apps/kg/modules/drill-simulasi/section/content/content.tsx
  apps/kg/modules/drill-simulasi/section/content/index.ts
  apps/kg/modules/drill-simulasi/section/content/simulasion/history.tsx
  apps/kg/modules/drill-simulasi/section/content/simulasion/index.ts
  apps/kg/modules/drill-simulasi/section/content/simulasion/submisson.tsx
  apps/kg/modules/drill-simulasi/section/hero/index.ts
  apps/kg/modules/drill-simulasi/section/index.ts
  apps/kg/modules/drill-simulasi/store.ts
  apps/kg/modules/drill-simulasi/type.d.ts
  apps/kg/modules/semuafitur/store.ts
  apps/kg/pages/styles.css
Labels: enhancement

#149 Fix : deployment cs-vite not change
  apps/cs-vite/src/modules/user/ai-identity-scoring/index.tsx
Labels: documentation, CS

#151 feature : reschedule simulation
  apps/kg/modules/drill-simulasi/section/content/simulasion/submisson.tsx
  apps/kg/modules/drill-simulasi/section/reschedule/assets/afternoon.svg
  apps/kg/modules/drill-simulasi/section/reschedule/assets/calendar.svg
  apps/kg/modules/drill-simulasi/section/reschedule/assets/checked.svg
  apps/kg/modules/drill-simulasi/section/reschedule/assets/checklist.svg
  apps/kg/modules/drill-simulasi/section/reschedule/assets/dropdown.svg
  apps/kg/modules/drill-simulasi/section/reschedule/assets/dummyReschedule.svg
  apps/kg/modules/drill-simulasi/section/reschedule/assets/iconWarning.svg
  apps/kg/modules/drill-simulasi/section/reschedule/assets/pengajuan.svg
  apps/kg/modules/drill-simulasi/section/reschedule/assets/reschedule-jadwal.svg
  apps/kg/modules/drill-simulasi/section/reschedule/assets/warning.svg
  apps/kg/modules/drill-simulasi/section/reschedule/constant.ts
  apps/kg/modules/drill-simulasi/section/reschedule/hooks.ts
  apps/kg/modules/drill-simulasi/section/reschedule/index.ts
  apps/kg/modules/drill-simulasi/section/reschedule/loading.tsx
  apps/kg/modules/drill-simulasi/section/reschedule/module.tsx
  apps/kg/modules/drill-simulasi/section/reschedule/section/content.tsx
  apps/kg/modules/drill-simulasi/section/reschedule/section/dateTime.tsx
  apps/kg/modules/drill-simulasi/section/reschedule/section/rules.tsx
  apps/kg/modules/drill-simulasi/section/reschedule/store.ts
  apps/kg/modules/drill-simulasi/section/reschedule/type.d.ts
  apps/kg/pages/simulasi-drill-dan-assestment/[topic].tsx
  apps/kg/pages/simulasi-drill-dan-assestment/perubahan-jadwal/[topic].tsx
  libs/components/molecules/src/accordion/index.tsx
  libs/components/molecules/src/accordion/types.d.ts
Labels: enhancement

#154 Improvement/add user/cs vite
  apps/cs-vite/src/components/atoms/icons/ic-download.tsx
  apps/cs-vite/src/components/atoms/icons/ic-upload.tsx
  apps/cs-vite/src/modules/user/ai-capability-scoring/index.tsx
  apps/cs-vite/src/modules/user/ai-character-scoring/index.tsx
  apps/cs-vite/src/modules/user/ai-identity-scoring/index.tsx
Labels: documentation, CS

#155 improvement : add notif max size to uploader file
  apps/cs-vite/src/modules/user/ai-identity-scoring/index.tsx
Labels: documentation, CS

#162 Improvement : add file vercel.json
  apps/cs-vite/src/vercel.json
  libs/components/atoms/src/inputs/text/index.tsx
Labels: documentation, CS

#163 improvement: add studiku navbar
  apps/kg/modules/mystudy/index.tsx
  apps/kg/pages/studi-ku/index.tsx
Labels: enhancement

#164 feature: recode all discussion page
  apps/kg/modules/discussion-room/api.ts
  apps/kg/modules/discussion-room/assets/checked.svg
  apps/kg/modules/discussion-room/assets/close.svg
  apps/kg/modules/discussion-room/assets/delete.svg
  apps/kg/modules/discussion-room/assets/discusionIcon-dark.svg
  apps/kg/modules/discussion-room/assets/discusionIcon.svg
  apps/kg/modules/discussion-room/assets/dummyCourse.png
  apps/kg/modules/discussion-room/assets/edit.svg
  apps/kg/modules/discussion-room/assets/flag.svg
  apps/kg/modules/discussion-room/assets/folder.svg
  apps/kg/modules/discussion-room/assets/send.svg
  apps/kg/modules/discussion-room/assets/userIcon.svg
  apps/kg/modules/discussion-room/component/PopupModalCreateDiscussion.tsx
  apps/kg/modules/discussion-room/component/PopupModalDeleteDiscussion.tsx
  apps/kg/modules/discussion-room/component/PopupModalEditDiscussion.tsx
  apps/kg/modules/discussion-room/component/PopupModalReportDiscussion.tsx
  apps/kg/modules/discussion-room/component/PopupModalSuccessDiscussion.tsx
  apps/kg/modules/discussion-room/component/types.d.ts
  apps/kg/modules/discussion-room/content-section/Search.tsx
  apps/kg/modules/discussion-room/content-section/index.tsx
  apps/kg/modules/discussion-room/content-section/post/PostCard.tsx
  apps/kg/modules/discussion-room/content-section/post/PostOption.tsx
  apps/kg/modules/discussion-room/content-section/post/coment/add-coment.tsx
  apps/kg/modules/discussion-room/content-section/post/coment/hooks.ts
  apps/kg/modules/discussion-room/content-section/post/coment/index.tsx
  apps/kg/modules/discussion-room/content-section/post/coment/stores.ts
  apps/kg/modules/discussion-room/content-section/post/coment/type.d.ts
  apps/kg/modules/discussion-room/content-section/post/hooks.ts
  apps/kg/modules/discussion-room/content-section/post/index.tsx
  apps/kg/modules/discussion-room/hero-section/index.tsx
  apps/kg/modules/discussion-room/hooks/useCreateDiscussion.ts
  apps/kg/modules/discussion-room/hooks/useDiscussionId.ts
  apps/kg/modules/discussion-room/hooks/useGetAllDiscussion.ts
  apps/kg/modules/discussion-room/hooks/useGetDiscussionById.ts
  apps/kg/modules/discussion-room/hooks/usePopupCreateDiscussionStatus.ts
  apps/kg/modules/discussion-room/hooks/usePopupDeleteDiscussionStatus.ts
  apps/kg/modules/discussion-room/hooks/usePopupEditDiscussionStatus.ts
  apps/kg/modules/discussion-room/hooks/usePopupGetDiscussion.ts
  apps/kg/modules/discussion-room/hooks/usePopupReportDiscussionStatus.ts
  apps/kg/modules/discussion-room/hooks/usePopupSuccessDiscussionStatus.ts
  apps/kg/modules/discussion-room/index.tsx
  apps/kg/modules/discussion-room/stores.ts
  apps/kg/modules/discussion-room/types.d.ts
Labels: enhancement

#165 Bugfixing/fix name variable/vite cs
  apps/cs-vite/src/main.tsx
  apps/cs-vite/src/modules/auth/login/api.ts
  apps/cs-vite/src/modules/auth/login/hooks.ts
  apps/cs-vite/src/modules/auth/login/index.tsx
  apps/cs-vite/src/modules/auth/login/types.d.ts
  apps/cs-vite/src/modules/user/add-data/add-data.tsx
  apps/cs-vite/src/modules/user/add-data/ai-capability-scoring/index.tsx
  apps/cs-vite/src/modules/user/add-data/ai-character-scoring/index.tsx
  apps/cs-vite/src/modules/user/add-data/ai-identity-scoring/index.tsx
  apps/cs-vite/src/modules/user/edit-data/ai-capability-scoring/index.tsx
  apps/cs-vite/src/modules/user/edit-data/ai-character-scoring/index.tsx
  apps/cs-vite/src/modules/user/edit-data/ai-identity-scoring/index.tsx
  apps/cs-vite/src/modules/user/edit-data/edit-data.tsx
  apps/cs-vite/src/modules/user/table.tsx
  apps/cs-vite/src/pages/user/add-data.tsx
  apps/cs-vite/src/pages/user/edit-data.tsx
  apps/cs-vite/src/routers/index.tsx
  apps/cs-vite/src/services/api.ts
  apps/cs-vite/src/services/token.ts
  libs/components/atoms/src/inputs/text/index.tsx
Labels: documentation, CS

#169 feature : mystudy discussion forum UI (KG)
  apps/kg/modules/mystudy/discussion/assets/circle.svg
  apps/kg/modules/mystudy/discussion/assets/comment.svg
  apps/kg/modules/mystudy/discussion/assets/delete.svg
  apps/kg/modules/mystudy/discussion/assets/down.svg
  apps/kg/modules/mystudy/discussion/assets/edit.svg
  apps/kg/modules/mystudy/discussion/assets/file.svg
  apps/kg/modules/mystudy/discussion/assets/like.svg
  apps/kg/modules/mystudy/discussion/assets/more.svg
  apps/kg/modules/mystudy/discussion/assets/profile-dummy.svg
  apps/kg/modules/mystudy/discussion/assets/redo.svg
  apps/kg/modules/mystudy/discussion/assets/send.svg
  apps/kg/modules/mystudy/discussion/components/card/comment/card.tsx
  apps/kg/modules/mystudy/discussion/components/card/comment/hooks.ts
  apps/kg/modules/mystudy/discussion/components/card/comment/index.ts
  apps/kg/modules/mystudy/discussion/components/card/comment/store.ts
  apps/kg/modules/mystudy/discussion/components/card/comment/types.d.ts
  apps/kg/modules/mystudy/discussion/components/card/discussion/card.tsx
  apps/kg/modules/mystudy/discussion/components/card/discussion/index.ts
  apps/kg/modules/mystudy/discussion/components/card/type.d.ts
  apps/kg/modules/mystudy/discussion/components/like-comment/index.ts
  apps/kg/modules/mystudy/discussion/components/like-comment/section.tsx
  apps/kg/modules/mystudy/discussion/components/modal/index.ts
  apps/kg/modules/mystudy/discussion/components/modal/modal.tsx
  apps/kg/modules/mystudy/discussion/components/modal/pop-up/index.ts
  apps/kg/modules/mystudy/discussion/components/modal/pop-up/popup.tsx
  apps/kg/modules/mystudy/discussion/components/modal/pop-up/types.d.ts
  apps/kg/modules/mystudy/discussion/components/modal/types.d.ts
  apps/kg/modules/mystudy/discussion/index.ts
  apps/kg/modules/mystudy/discussion/module.tsx
  apps/kg/modules/mystudy/discussion/section/content/content.tsx
  apps/kg/modules/mystudy/discussion/section/content/index.ts
  apps/kg/modules/mystudy/discussion/section/sidebar/hooks.ts
  apps/kg/modules/mystudy/discussion/section/sidebar/index.ts
  apps/kg/modules/mystudy/discussion/section/sidebar/sidebar.tsx
  apps/kg/modules/mystudy/discussion/section/sidebar/store.ts
  apps/kg/modules/mystudy/discussion/section/sidebar/types.d.ts
  apps/kg/pages/studi-ku/[detail-matkul]/diskusi/index.tsx
Labels: enhancement

#170 feature: fix folder structure
  apps/kg/modules/index.ts
  apps/kg/modules/profile/section/edit-profile/EditProfile.tsx
  apps/kg/modules/study-plan/choice-faculty/index.tsx
  apps/kg/modules/study-plan/index.ts
  apps/kg/modules/study-plan/study-program/index.tsx
  apps/kg/modules/study-plan/submission-contract/index.tsx
  apps/kg/pages/profile/index.tsx
  apps/kg/pages/profile/reset-password/index.tsx
  apps/kg/pages/rencana-studi/fakultas/[...slug].tsx
  apps/kg/pages/rencana-studi/index.tsx
Labels: enhancement, KG

#178 Feature : training plan integration
  apps/lxp/modules/auth/login/api.ts
  apps/lxp/modules/auth/login/login-popup/login-popup.tsx
  apps/lxp/modules/auth/login/module.tsx
  apps/lxp/modules/auth/login/types.d.ts
  apps/lxp/modules/auth/register/module.tsx
  apps/lxp/modules/auth/register/types.d.ts
  apps/lxp/modules/common/assets/notFound.svg
  apps/lxp/modules/common/not-found/icon.tsx
  apps/lxp/modules/common/not-found/index.ts
  apps/lxp/modules/common/not-found/module.tsx
  apps/lxp/modules/common/not-found/types.d.ts
  apps/lxp/modules/common/provider/ClientProvider/provider.tsx
  apps/lxp/modules/training-information/api.ts
  apps/lxp/modules/training-information/header/header.tsx
  apps/lxp/modules/training-information/hook.ts
  apps/lxp/modules/training-information/main/table/table.tsx
  apps/lxp/modules/training-information/types.d.ts
  apps/lxp/modules/training-plan/header/header.tsx
  apps/lxp/modules/training-plan/main/api.ts
  apps/lxp/modules/training-plan/main/hook.ts
  apps/lxp/modules/training-plan/main/loading.tsx
  apps/lxp/modules/training-plan/main/main.tsx
  apps/lxp/modules/training-plan/main/types.d.ts
  apps/lxp/pages/api/auth/[...nextauth].ts
  apps/lxp/pages/api/auth/login.ts
  apps/lxp/services/types.d.ts
Labels: enhancement

#182 feature : mystudy module UI (KG)
  apps/kg/modules/mystudy/module/assets/button-play.svg
  apps/kg/modules/mystudy/module/assets/iconDoc.svg
  apps/kg/modules/mystudy/module/components/button/button.tsx
  apps/kg/modules/mystudy/module/components/button/index.ts
  apps/kg/modules/mystudy/module/components/button/type.d.ts
  apps/kg/modules/mystudy/module/hooks.ts
  apps/kg/modules/mystudy/module/index.ts
  apps/kg/modules/mystudy/module/module-content/hooks.ts
  apps/kg/modules/mystudy/module/module-content/index.ts
  apps/kg/modules/mystudy/module/module-content/module.tsx
  apps/kg/modules/mystudy/module/module-content/store.ts
  apps/kg/modules/mystudy/module/module-content/types.d.ts
  apps/kg/modules/mystudy/module/module.tsx
  apps/kg/modules/mystudy/module/store.ts
  apps/kg/modules/mystudy/module/type.d.ts
  apps/kg/pages/studi-ku/[detail-matkul]/modul/index.tsx
  apps/kg/pages/studi-ku/[detail-matkul]/modul/modul1/index.tsx
Labels: enhancement

#189 feature : migrate discussion room lxp
  apps/lxp/modules/discussion-room/assets/discussion.tsx
  apps/lxp/modules/discussion-room/assets/index.ts
  apps/lxp/modules/discussion-room/const.ts
  apps/lxp/modules/discussion-room/content/index.ts
  apps/lxp/modules/discussion-room/content/post/index.ts
  apps/lxp/modules/discussion-room/content/post/modal/delete-comfirm/index.ts
  apps/lxp/modules/discussion-room/content/post/modal/delete-comfirm/section.tsx
  apps/lxp/modules/discussion-room/content/post/modal/index.ts
  apps/lxp/modules/discussion-room/content/post/modal/post-report-success/index.ts
  apps/lxp/modules/discussion-room/content/post/modal/post-report-success/section.tsx
  apps/lxp/modules/discussion-room/content/post/modal/post-report/index.ts
  apps/lxp/modules/discussion-room/content/post/modal/post-report/section.tsx
  apps/lxp/modules/discussion-room/content/post/modal/post-spam/index.ts
  apps/lxp/modules/discussion-room/content/post/modal/post-spam/section.tsx
  apps/lxp/modules/discussion-room/content/post/option/index.ts
  apps/lxp/modules/discussion-room/content/post/option/section.tsx
  apps/lxp/modules/discussion-room/content/post/option/types.d.ts
  apps/lxp/modules/discussion-room/content/post/section.tsx
  apps/lxp/modules/discussion-room/content/post/types.d.ts
  apps/lxp/modules/discussion-room/content/section.tsx
  apps/lxp/modules/discussion-room/content/store.ts
  apps/lxp/modules/discussion-room/hero/index.ts
  apps/lxp/modules/discussion-room/hero/section.tsx
  apps/lxp/modules/discussion-room/index.ts
  apps/lxp/modules/discussion-room/module.tsx
  apps/lxp/modules/index.ts
  apps/lxp/pages/ruang-diskusi/index.tsx
Labels: enhancement, LXP

#190 feature: change change-password validation
  apps/kg/modules/profile/section/reset-password/ResetPassword.tsx
  apps/kg/modules/profile/section/reset-password/api.ts
Labels: enhancement, KG

#191 migrate leaderboard pages
  apps/lxp/modules/administrations/common/PrivatInformationAccordion.tsx
  apps/lxp/modules/administrations/section/ContentAdministration/content.tsx
  apps/lxp/modules/administrations/type.d.ts
  apps/lxp/modules/leaderboard/assets/avatar.svg
  apps/lxp/modules/leaderboard/assets/building.svg
  apps/lxp/modules/leaderboard/assets/chat.svg
  apps/lxp/modules/leaderboard/assets/circle.svg
  apps/lxp/modules/leaderboard/assets/clock.svg
  apps/lxp/modules/leaderboard/assets/crown.svg
  apps/lxp/modules/leaderboard/assets/like.svg
  apps/lxp/modules/leaderboard/assets/medal-1.svg
  apps/lxp/modules/leaderboard/assets/medal-2.svg
  apps/lxp/modules/leaderboard/assets/medal-3.svg
  apps/lxp/modules/leaderboard/assets/medal.svg
  apps/lxp/modules/leaderboard/assets/module-four.svg
  apps/lxp/modules/leaderboard/common/PopupProfile.tsx
  apps/lxp/modules/leaderboard/common/filter.tsx
  apps/lxp/modules/leaderboard/hooks.ts
  apps/lxp/modules/leaderboard/index.ts
  apps/lxp/modules/leaderboard/module.tsx
  apps/lxp/modules/leaderboard/section/ContentSection.tsx
  apps/lxp/modules/leaderboard/section/RankingSection.tsx
  apps/lxp/modules/leaderboard/store.tsx
  apps/lxp/modules/leaderboard/type.d.ts
  apps/lxp/pages/papan-skor/index.tsx
Labels: LXP

#194 feature: guide book
  apps/kg/modules/administration/constant.ts
  apps/kg/modules/guide/guide-book/const.ts
  apps/kg/modules/guide/guide-book/content/content.tsx
  apps/kg/modules/guide/guide-book/content/index.ts
  apps/kg/modules/guide/guide-book/content/store.ts
  apps/kg/modules/guide/guide-book/hero/hero.tsx
  apps/kg/modules/guide/guide-book/hero/index.ts
  apps/kg/modules/guide/guide-book/index.ts
  apps/kg/modules/guide/guide-book/loading.tsx
  apps/kg/modules/guide/guide-book/module.tsx
  apps/kg/modules/guide/index.tsx
  apps/kg/modules/guide/landing/const.ts
  apps/kg/modules/guide/landing/faq/faq.tsx
  apps/kg/modules/guide/landing/faq/index.ts
  apps/kg/modules/guide/landing/faq/store.ts
  apps/kg/modules/guide/landing/guide/guide.tsx
  apps/kg/modules/guide/landing/guide/index.ts
  apps/kg/modules/guide/landing/guide/store.ts
  apps/kg/modules/guide/landing/hero/hero.tsx
  apps/kg/modules/guide/landing/hero/index.ts
  apps/kg/modules/guide/landing/index.ts
  apps/kg/modules/guide/landing/loading.tsx
  apps/kg/modules/guide/landing/module.tsx
  apps/kg/modules/guide/registration-book/another-guide/anotherGuide.tsx
  apps/kg/modules/guide/registration-book/another-guide/index.ts
  apps/kg/modules/guide/registration-book/another-guide/store.ts
  apps/kg/modules/guide/registration-book/const.ts
  apps/kg/modules/guide/registration-book/content/content.tsx
  apps/kg/modules/guide/registration-book/content/index.ts
  apps/kg/modules/guide/registration-book/hero/hero.tsx
  apps/kg/modules/guide/registration-book/hero/index.ts
  apps/kg/modules/guide/registration-book/index.ts
  apps/kg/modules/guide/registration-book/loading.tsx
  apps/kg/modules/guide/registration-book/module.tsx
  apps/kg/modules/index.ts
  apps/kg/pages/panduan/buku-panduan/index.tsx
  apps/kg/pages/panduan/buku-panduan/panduan-pendaftaran/index.tsx
  apps/kg/pages/panduan/index.tsx
Labels: enhancement, KG

#197 feature: migrate unique-event-detail lxp
  apps/kg/modules/study-plan/choice-faculty/ChoiceFaculty.tsx
  apps/kg/modules/study-plan/study-program/StudyProgram.tsx
  apps/kg/modules/study-plan/study-program/api.ts
  apps/kg/pages/rencana-studi/fakultas/[id_fakultas].tsx
  apps/lxp/modules/index.ts
  apps/lxp/modules/unique-event-detail/UniqueEventDetail.tsx
  apps/lxp/modules/unique-event-detail/event-banner/EventDetailBanner.tsx
  apps/lxp/modules/unique-event-detail/event-banner/banner-information/EventBannerInformation.tsx
  apps/lxp/modules/unique-event-detail/event-banner/banner-registered/RegisteredEventModal.tsx
  apps/lxp/modules/unique-event-detail/event-tab/EventDetailTab.tsx
  apps/lxp/modules/unique-event-detail/event-tab/event-card/EventCard.tsx
  apps/lxp/modules/unique-event-detail/event-tab/event-contact/EventContactCard.tsx
  apps/lxp/modules/unique-event-detail/event-tab/event-description/EventDetaiDescription.tsx
  apps/lxp/modules/unique-event-detail/event-tab/event-related/RelatedEvent.tsx
  apps/lxp/modules/unique-event-detail/index.ts
  apps/lxp/modules/unique-event-detail/types.d.ts
  apps/lxp/modules/unique-event/UniqueEventModule.tsx
  apps/lxp/modules/unique-event/constant.tsx
  apps/lxp/modules/unique-event/event-content/UniqueEventContent.tsx
  apps/lxp/modules/unique-event/event-search/UniqueEventSearch.tsx
  apps/lxp/modules/unique-event/event-sidebar/UniqueEventSidebar.tsx
  apps/lxp/modules/unique-event/event-sidebar/header/UniqueSidebarHeader.tsx
  apps/lxp/modules/unique-event/event-sidebar/options/UniqueSidebarOptions.tsx
  apps/lxp/modules/unique-event/index.ts
  apps/lxp/modules/unique-event/store.ts
  apps/lxp/pages/acara-unik/[slug]/index.tsx
  apps/lxp/pages/acara-unik/detail/[slug].tsx
  apps/lxp/pages/acara-unik/index.tsx
Labels: enhancement, KG

#198 Feature : migrate drill simulation lxp
  apps/lxp/modules/drill-simulation/header/index.ts
  apps/lxp/modules/drill-simulation/header/section.tsx
  apps/lxp/modules/drill-simulation/index.ts
  apps/lxp/modules/drill-simulation/main/const.ts
  apps/lxp/modules/drill-simulation/main/history/index.ts
  apps/lxp/modules/drill-simulation/main/history/modal/assets/finished.svg
  apps/lxp/modules/drill-simulation/main/history/modal/assets/pending.svg
  apps/lxp/modules/drill-simulation/main/history/modal/assets/sent.svg
  apps/lxp/modules/drill-simulation/main/history/modal/index.ts
  apps/lxp/modules/drill-simulation/main/history/modal/section.tsx
  apps/lxp/modules/drill-simulation/main/history/modal/types.d.ts
  apps/lxp/modules/drill-simulation/main/history/section.tsx
  apps/lxp/modules/drill-simulation/main/history/store.ts
  apps/lxp/modules/drill-simulation/main/index.ts
  apps/lxp/modules/drill-simulation/main/request/index.ts
  apps/lxp/modules/drill-simulation/main/request/section.tsx
  apps/lxp/modules/drill-simulation/main/request/store.ts
  apps/lxp/modules/drill-simulation/main/section.tsx
  apps/lxp/modules/drill-simulation/main/store.ts
  apps/lxp/modules/drill-simulation/module.tsx
  apps/lxp/modules/index.ts
  apps/lxp/modules/my-training/module.tsx
  apps/lxp/modules/request-simulation/const.ts
  apps/lxp/modules/request-simulation/index.ts
  apps/lxp/modules/request-simulation/main/index.ts
  apps/lxp/modules/request-simulation/main/instruction/index.ts
  apps/lxp/modules/request-simulation/main/instruction/section.tsx
  apps/lxp/modules/request-simulation/main/section.tsx
  apps/lxp/modules/request-simulation/main/store.ts
  apps/lxp/modules/request-simulation/module.tsx
  apps/lxp/pages/drill-simulasi/index.tsx
  apps/lxp/pages/drill-simulasi/pengajuan-jadwal/[id].tsx
Labels: enhancement, LXP

#196 feature : kontrak studi
  apps/kg/modules/study-contract/submissionContractStudy/kontrak.tsx
  libs/components/atoms/src/button/index.tsx
  libs/components/molecules/src/globalButton/index.tsx
  libs/components/molecules/src/globalButton/type.d.ts
  libs/components/molecules/src/index.ts
  package.json
Labels: KG

#199 feature: create hooks, types, and api getMajorById
  apps/kg/modules/study-plan/study-program/api.ts
  apps/kg/modules/study-plan/study-program/hooks.ts
  apps/kg/modules/study-plan/study-program/types.d.ts
Labels: enhancement, KG

#202 Bug Fix : Fixing Error
  apps/cs-vite/src/assets/.gitkeep
  apps/cs-vite/src/components/atoms/icons/ic-calendar.tsx
  apps/cs-vite/src/components/atoms/search/index.tsx
  apps/cs-vite/src/components/atoms/search/types.d.ts
  apps/cs-vite/src/components/molecules/input/date-input/index.tsx
  apps/cs-vite/src/components/molecules/input/date-range-picker/index.tsx
  apps/cs-vite/src/modules/quota/alocation-quota.tsx
  apps/cs-vite/src/modules/quota/history-alocation.tsx
  apps/cs-vite/src/modules/report/index.tsx
  apps/cs-vite/src/modules/report/report.tsx
  apps/cs-vite/src/modules/report/table.tsx
  apps/cs-vite/src/modules/user/index.tsx
  package.json
  yarn.lock
Labels: documentation, enhancement, CS

#203 feature: integrating getMajorById kg
  apps/kg/modules/study-plan/study-program/StudyProgram.tsx
  apps/kg/modules/study-plan/study-program/hooks.ts
Labels: enhancement, KG

#204 feature : analytic page UI (KG)
  apps/kg/modules/analytic/assets/Name.svg
  apps/kg/modules/analytic/assets/building-1.svg
  apps/kg/modules/analytic/assets/building-2.svg
  apps/kg/modules/analytic/assets/home.svg
  apps/kg/modules/analytic/assets/list-bullets.svg
  apps/kg/modules/analytic/assets/profile-avatar-example.svg
  apps/kg/modules/analytic/const.ts
  apps/kg/modules/analytic/index.ts
  apps/kg/modules/analytic/main/chart/chart.tsx
  apps/kg/modules/analytic/main/chart/index.ts
  apps/kg/modules/analytic/main/icon/assets/Report-rafiki 1.svg
  apps/kg/modules/analytic/main/icon/assets/report.svg
  apps/kg/modules/analytic/main/icon/icon.tsx
  apps/kg/modules/analytic/main/icon/index.ts
  apps/kg/modules/analytic/main/index.ts
  apps/kg/modules/analytic/main/main.tsx
  apps/kg/modules/analytic/main/performance/index.ts
  apps/kg/modules/analytic/main/performance/performance.tsx
  apps/kg/modules/analytic/main/recent-performance/index.ts
  apps/kg/modules/analytic/main/recent-performance/recent.tsx
  apps/kg/modules/analytic/module.tsx
  apps/kg/modules/analytic/sidebar/content/content.tsx
  apps/kg/modules/analytic/sidebar/content/index.ts
  apps/kg/modules/analytic/sidebar/header/header.tsx
  apps/kg/modules/analytic/sidebar/header/index.ts
  apps/kg/modules/analytic/sidebar/index.ts
  apps/kg/modules/analytic/sidebar/sidebar.tsx
  apps/kg/pages/analitik/index.tsx
Labels: enhancement, KG

#213 feature : profile change password
  apps/lxp/modules/profile/main/change-password/index.ts
  apps/lxp/modules/profile/main/change-password/section.tsx
  apps/lxp/modules/profile/main/cv-portofolio/index.ts
  apps/lxp/modules/profile/main/cv-portofolio/section.tsx
  apps/lxp/modules/profile/main/index.ts
  apps/lxp/modules/profile/module.tsx
  apps/lxp/modules/profile/sidebar/section.tsx
  apps/lxp/pages/profile/cv-portofolio.tsx
  apps/lxp/pages/profile/ubah-password.tsx
Labels: enhancement, LXP

#214 migrate guide video - registration video
  apps/lxp/modules/guide-guide video/assets/document.svg
  apps/lxp/modules/guide-guide video/assets/video.svg
  apps/lxp/modules/guide-guide video/const.ts
  apps/lxp/modules/guide-guide video/hooks.ts
  apps/lxp/modules/guide-guide video/index.ts
  apps/lxp/modules/guide-guide video/module.tsx
  apps/lxp/modules/guide-guide video/section/ContentSection.tsx
  apps/lxp/modules/guide-guide video/section/Description.tsx
  apps/lxp/modules/guide-guide video/section/ListVideo.tsx
  apps/lxp/modules/guide-guide video/section/YoutubeSection.tsx
  apps/lxp/modules/guide-guide video/store.ts
  apps/lxp/modules/guide-guide video/type.d.ts
  apps/lxp/pages/panduan/video-panduan/[videoId]/index.tsx
Labels: LXP

#220 feature : mystudy major integration
  apps/kg/modules/mystudy/api.ts
  apps/kg/modules/mystudy/assets/mahasiswa.svg
  apps/kg/modules/mystudy/assets/matkul.svg
  apps/kg/modules/mystudy/assets/semester.svg
  apps/kg/modules/mystudy/assets/sks.svg
  apps/kg/modules/mystudy/hooks.ts
  apps/kg/modules/mystudy/index.ts
  apps/kg/modules/mystudy/index.tsx
  apps/kg/modules/mystudy/mystudy-module/api.ts
  apps/kg/modules/mystudy/mystudy-module/assets/Dummy.svg
  apps/kg/modules/mystudy/mystudy-module/assets/content-paper-edit.svg
  apps/kg/modules/mystudy/mystudy-module/assets/mahasiswa.svg
  apps/kg/modules/mystudy/mystudy-module/assets/matkul.svg
  apps/kg/modules/mystudy/mystudy-module/assets/search.svg
  apps/kg/modules/mystudy/mystudy-module/assets/semester.svg
  apps/kg/modules/mystudy/mystudy-module/assets/sks.svg
  apps/kg/modules/mystudy/mystudy-module/hooks.ts
  apps/kg/modules/mystudy/mystudy-module/index.ts
  apps/kg/modules/mystudy/mystudy-module/major/const.ts
  apps/kg/modules/mystudy/mystudy-module/major/index.ts
  apps/kg/modules/mystudy/mystudy-module/major/section.tsx
  apps/kg/modules/mystudy/mystudy-module/module.tsx
  apps/kg/modules/mystudy/mystudy-module/subject/index.ts
  apps/kg/modules/mystudy/mystudy-module/subject/section.tsx
  apps/kg/modules/mystudy/mystudy-module/types.d.ts
  apps/kg/modules/mystudy/store.ts
  apps/kg/modules/mystudy/subject/api.ts
  apps/kg/modules/mystudy/subject/types.d.ts
  apps/kg/modules/mystudy/typed.d.ts
  apps/kg/modules/mystudy/types.d.ts
  apps/kg/pages/api/mystudy/index.ts
  apps/kg/pages/studi-ku/index.tsx
Labels: enhancement, KG

#227 feature: getAllDiscussion kg
  apps/kg/modules/discussion-room/content/section.tsx
Labels: question, KG

#244 improvement: add change
  apps/kg/modules/guide/guide-dictionary/sidebar/sidebar.tsx
Labels: enhancement, KG

#254 feature : build mystudy major and subject API integration
  apps/kg/modules/mystudy/mystudy-module/assets/orang-bingung.svg
  apps/kg/modules/mystudy/mystudy-module/major/section.tsx
  apps/kg/modules/mystudy/mystudy-module/module.tsx
  apps/kg/modules/mystudy/mystudy-module/subject/section.tsx
  apps/kg/modules/mystudy/subject-details/type.d.ts
  apps/kg/pages/api/mystudy/subject-details/index.ts
Labels: enhancement, KG

#257 feature: integrating getCommentById kg
  apps/kg/modules/discussion-room/content/CommentSection.tsx
  apps/kg/modules/discussion-room/content/api.ts
  apps/kg/modules/discussion-room/content/hooks.ts
  apps/kg/modules/discussion-room/content/section.tsx
  apps/kg/modules/discussion-room/content/types.d.ts
  apps/lxp/modules/glimpse-knowledge/index.ts
  apps/lxp/modules/glimpse-knowledge/index.tsx
  apps/lxp/modules/glimpse-knowledge/layout/GlimpseKnowledgeLayoutPage.tsx
  apps/lxp/modules/glimpse-knowledge/layout/Main/Card/RelatedGlimpseKnowledgeCard.tsx
  apps/lxp/modules/glimpse-knowledge/layout/Main/GlimpseKnowledgeLayoutMain.tsx
  apps/lxp/modules/glimpse-knowledge/layout/index.ts
  apps/lxp/modules/glimpse-knowledge/layout/module.tsx
  apps/lxp/pages/sekilas-ilmu/[slug]/index.tsx
  apps/lxp/pages/sekilas-ilmu/index.tsx
Labels: enhancement, KG

#258 Improvement : fixed consistent named export for icon and fix path whe…
  apps/cs-vite/src/components/atoms/icons/ic-dashboard.tsx
  apps/cs-vite/src/components/atoms/icons/ic-download.tsx
  apps/cs-vite/src/components/atoms/icons/ic-dropdown.tsx
  apps/cs-vite/src/components/atoms/icons/ic-logout.tsx
  apps/cs-vite/src/components/atoms/icons/ic-map.tsx
  apps/cs-vite/src/components/atoms/icons/ic-next.tsx
  apps/cs-vite/src/components/atoms/icons/ic-prev.tsx
  apps/cs-vite/src/components/atoms/icons/ic-quota.tsx
  apps/cs-vite/src/components/atoms/icons/ic-report.tsx
  apps/cs-vite/src/components/atoms/icons/ic-request.tsx
  apps/cs-vite/src/components/atoms/icons/ic-search.tsx
  apps/cs-vite/src/components/atoms/icons/ic-table.tsx
  apps/cs-vite/src/components/atoms/icons/ic-toggle.tsx
  apps/cs-vite/src/components/atoms/icons/ic-upload.tsx
  apps/cs-vite/src/components/atoms/icons/ic-user.tsx
  apps/cs-vite/src/components/atoms/icons/index.ts
  apps/cs-vite/src/components/atoms/index.ts
  apps/cs-vite/src/components/atoms/pagination/index.tsx
  apps/cs-vite/src/components/atoms/search/index.tsx
  apps/cs-vite/src/components/organisms/card-chart/location-tract.tsx
  apps/cs-vite/src/components/organisms/navbar/index.tsx
  apps/cs-vite/src/components/organisms/navbar/navbar-sekeleton.tsx
  apps/cs-vite/src/components/organisms/sidebar/index.tsx
  apps/cs-vite/src/modules/report/table.tsx
  apps/cs-vite/src/modules/request/get-request.tsx
  apps/cs-vite/src/modules/request/request.tsx
  apps/cs-vite/src/modules/request/table.tsx
  apps/cs-vite/src/modules/user/add-data/add-data.tsx
  apps/cs-vite/src/modules/user/add-data/ai-capability-scoring/index.tsx
  apps/cs-vite/src/modules/user/add-data/ai-character-scoring/index.tsx
  apps/cs-vite/src/modules/user/edit-data/ai-capability-scoring/index.tsx
  apps/cs-vite/src/modules/user/edit-data/ai-character-scoring/index.tsx
  apps/cs-vite/src/modules/user/table.tsx
Labels: documentation, CS

#265 feature : migrate dashboard UI lxp
  apps/lxp/modules/dashboard/article/carousel/index.ts
  apps/lxp/modules/dashboard/article/carousel/section.tsx
  apps/lxp/modules/dashboard/article/index.ts
  apps/lxp/modules/dashboard/article/section.tsx
  apps/lxp/modules/dashboard/calendar/header/index.ts
  apps/lxp/modules/dashboard/calendar/header/section.tsx
  apps/lxp/modules/dashboard/calendar/header/store.ts
  apps/lxp/modules/dashboard/calendar/index.ts
  apps/lxp/modules/dashboard/calendar/main/index.ts
  apps/lxp/modules/dashboard/calendar/main/section.tsx
  apps/lxp/modules/dashboard/calendar/section.tsx
  apps/lxp/modules/dashboard/const.ts
  apps/lxp/modules/dashboard/event/index.ts
  apps/lxp/modules/dashboard/event/section.tsx
  apps/lxp/modules/dashboard/index.ts
  apps/lxp/modules/dashboard/leaderboard/assets/bigThropyIcon.tsx
  apps/lxp/modules/dashboard/leaderboard/assets/bronzeMedal.tsx
  apps/lxp/modules/dashboard/leaderboard/assets/goldMedal.tsx
  apps/lxp/modules/dashboard/leaderboard/assets/index.ts
  apps/lxp/modules/dashboard/leaderboard/assets/silverMedal.tsx
  apps/lxp/modules/dashboard/leaderboard/index.ts
  apps/lxp/modules/dashboard/leaderboard/section.tsx
  apps/lxp/modules/dashboard/module.tsx
  apps/lxp/modules/dashboard/progress/card/index.ts
  apps/lxp/modules/dashboard/progress/card/section.tsx
  apps/lxp/modules/dashboard/progress/card/types.d.ts
  apps/lxp/modules/dashboard/progress/index.ts
  apps/lxp/modules/dashboard/progress/section.tsx
  apps/lxp/modules/dashboard/resume/assets/clockIcon.tsx
  apps/lxp/modules/dashboard/resume/assets/homeIcon.tsx
  apps/lxp/modules/dashboard/resume/assets/index.ts
  apps/lxp/modules/dashboard/resume/assets/labIcon.tsx
  apps/lxp/modules/dashboard/resume/assets/thropyIcon.tsx
  apps/lxp/modules/dashboard/resume/index.ts
  apps/lxp/modules/dashboard/resume/section.tsx
  apps/lxp/modules/dashboard/task/index.ts
  apps/lxp/modules/dashboard/task/section.tsx
  apps/lxp/modules/index.ts
  apps/lxp/pages/dashboard/index.tsx
  apps/lxp/pages/styles.css
Labels: enhancement, LXP

#266 fixing login and logout lxp
  apps/lxp/modules/profile/hooks.ts
Labels: LXP

#267 fix: uncloseable edit popup discussion
  apps/lxp/modules/discussion-room/content/post/modal/index.ts
  apps/lxp/modules/discussion-room/content/post/modal/post-edit/icons/fileIcon.tsx
  apps/lxp/modules/discussion-room/content/post/modal/post-edit/icons/index.ts
  apps/lxp/modules/discussion-room/content/post/modal/post-edit/index.ts
  apps/lxp/modules/discussion-room/content/post/modal/post-edit/section.tsx
  apps/lxp/modules/discussion-room/content/post/modal/post-edit/types.d.ts
  apps/lxp/modules/discussion-room/content/section.tsx
  libs/components/atoms/src/inputs/text/index.tsx
Labels: bug, enhancement, LXP

#269 feature : add page /kontark-krs/detail
  apps/kg/modules/study-contract/details/hooks.ts
  apps/kg/modules/study-contract/details/index.tsx
  apps/kg/modules/study-contract/details/kontrak-krs/assets/Confirm.svg
  apps/kg/modules/study-contract/details/kontrak-krs/assets/Success.svg
  apps/kg/modules/study-contract/details/kontrak-krs/assets/example1.svg
  apps/kg/modules/study-contract/details/kontrak-krs/assets/example2.svg
  apps/kg/modules/study-contract/details/kontrak-krs/index.tsx
  apps/kg/modules/study-contract/details/kontrak-krs/tabel.tsx
  apps/kg/modules/study-contract/details/stores.ts
  apps/kg/modules/study-contract/details/type.d.ts
  apps/kg/pages/kontrak-krs/[detail]/index.tsx
Labels: KG

#275 improvement: post file administration
  apps/kg/modules/administration/api.ts
  apps/kg/modules/administration/file-information/index.tsx
  apps/kg/modules/administration/jobs-information/index.tsx
  apps/kg/modules/administration/private-information/index.tsx
  apps/kg/modules/administration/types.d.ts
  apps/kg/modules/profile/section/edit-profile/section.tsx
Labels: enhancement, KG

#268 integration api administration
  apps/lxp/modules/administrations/common/PrivatInformationAccordion.tsx
  apps/lxp/modules/administrations/section/TitleAdministration/title.tsx
Labels: LXP

#294 Bugfixing : Fixing function uploader on add user and edit user
  apps/cs/src/components/atoms/icons/ic-notif.tsx
  apps/cs/src/components/atoms/icons/index.ts
  apps/cs/src/modules/user/add-data/add-data.tsx
  apps/cs/src/modules/user/add-data/ai-capability-scoring/index.tsx
  apps/cs/src/modules/user/add-data/ai-character-scoring/index.tsx
  apps/cs/src/modules/user/add-data/ai-identity-scoring/index.tsx
  apps/cs/src/modules/user/edit-data/ai-capability-scoring/index.tsx
  apps/cs/src/modules/user/edit-data/ai-character-scoring/index.tsx
  apps/cs/src/modules/user/edit-data/ai-identity-scoring/index.tsx
  apps/cs/src/modules/user/edit-data/edit-data.tsx
  apps/cs/src/modules/user/hooks.ts
  apps/cs/src/modules/user/store.ts
  apps/cs/src/modules/user/types.d.ts
  libs/components/atoms/src/inputs/upload/index.tsx
Labels: bug, CS

#293 feature : create subject-details a.k.a get mystudy subject by id service api
  apps/kg/modules/mystudy/mystudy-module/subject/section.tsx
  apps/kg/modules/mystudy/quiz/module.tsx
  apps/kg/modules/mystudy/subject-details/api.ts
  apps/kg/modules/mystudy/subject-details/hooks.ts
  apps/kg/modules/mystudy/subject-details/module.tsx
  apps/kg/modules/mystudy/subject-details/session/index.ts
  apps/kg/modules/mystudy/subject-details/session/session.tsx
  apps/kg/modules/mystudy/subject-details/session/type.d.ts
Labels: enhancement, KG

#297 Improvement : icon on table user page and pagination
  apps/cs/src/components/atoms/icons/ic-check.tsx
  apps/cs/src/components/atoms/icons/ic-delete.tsx
  apps/cs/src/components/atoms/icons/ic-edit.tsx
  apps/cs/src/components/atoms/icons/ic-error.tsx
  apps/cs/src/components/atoms/icons/index.ts
  apps/cs/src/components/atoms/pagination/index.tsx
  apps/cs/src/components/atoms/search/index.tsx
  apps/cs/src/modules/user/index.tsx
  apps/cs/src/modules/user/store.ts
  apps/cs/src/modules/user/table.tsx
  apps/cs/src/modules/user/types.d.ts
Labels: documentation, CS

#303 improvement: Add full name and email in private adm
  apps/kg/modules/administration/jobs-information/index.tsx
  apps/kg/modules/administration/private-information/index.tsx
  libs/components/atoms/src/inputs/select/index.tsx
  libs/components/atoms/src/inputs/select/types.d.ts
Labels: enhancement, KG

#312 migrate pages guide - home
  apps/lxp/modules/common/provider/ClientProvider/provider.tsx
  apps/lxp/modules/common/provider/types.d.ts
  apps/lxp/modules/guide/assets/buku-panduan.svg
  apps/lxp/modules/guide/assets/kamus.svg
  apps/lxp/modules/guide/assets/panduan-hero.svg
  apps/lxp/modules/guide/assets/search.svg
  apps/lxp/modules/guide/assets/video-player.svg
  apps/lxp/modules/guide/assets/video.svg
  apps/lxp/modules/guide/const.ts
  apps/lxp/modules/guide/index.ts
  apps/lxp/modules/guide/loading.tsx
  apps/lxp/modules/guide/module.tsx
  apps/lxp/modules/guide/section/content/faq.tsx
  apps/lxp/modules/guide/section/content/guide.tsx
  apps/lxp/modules/guide/section/hero/hero.tsx
  apps/lxp/modules/guide/section/index.ts
  apps/lxp/modules/guide/store.ts
  apps/lxp/pages/panduan/index.tsx
Labels: LXP

#318 Improvement: Validation accordion on add user page
  apps/cs/src/modules/user/add-data/ai-capability-scoring/index.tsx
  apps/cs/src/modules/user/add-data/ai-character-scoring/index.tsx
  apps/cs/src/modules/user/add-data/ai-identity-scoring/index.tsx
  apps/cs/src/modules/user/hooks.ts
  apps/cs/src/modules/user/store.ts
  apps/cs/src/modules/user/types.d.ts
Labels: documentation, CS

#321 feature : bug fix and profile integration lxp
  apps/lxp/modules/profile/main/edit-profile/api.ts
  apps/lxp/modules/profile/main/edit-profile/hook.ts
  apps/lxp/modules/profile/main/edit-profile/section.tsx
  apps/lxp/modules/profile/main/edit-profile/types.d.ts
  apps/lxp/modules/request-simulation/main/assets/day.tsx
  apps/lxp/modules/request-simulation/main/assets/index.ts
  apps/lxp/modules/request-simulation/main/assets/night.tsx
  apps/lxp/modules/request-simulation/main/index.ts
  apps/lxp/modules/request-simulation/main/section.tsx
  apps/lxp/modules/score-sertificate/main/score-summary-table/section.tsx
  libs/components/atoms/src/inputs/upload/index.tsx
Labels: enhancement, LXP

#323 Feature : edit profile integration lxp
  apps/lxp/modules/profile/main/edit-profile/api.ts
  apps/lxp/modules/profile/main/edit-profile/hook.ts
  apps/lxp/modules/profile/main/edit-profile/section.tsx
  apps/lxp/modules/profile/main/edit-profile/types.d.ts
  libs/components/atoms/src/inputs/select/index.tsx
Labels: enhancement, LXP

#329 improvement: update button on request page and font bold on title in every card's home page
  apps/cs/src/components/organisms/card-chart/age-track.tsx
  apps/cs/src/components/organisms/card-chart/location-tract.tsx
  apps/cs/src/components/organisms/card-chart/salary-track.tsx
  apps/cs/src/modules/home/history-request-section.tsx
  apps/cs/src/modules/quota/hooks.ts
  apps/cs/src/modules/quota/store.ts
  apps/cs/src/modules/request/process.tsx
  apps/cs/src/modules/request/request.tsx
  apps/cs/src/modules/request/store.ts
  apps/cs/src/modules/request/table.tsx
Labels: bug, CS

#315 feature: create forgot password
  apps/kg/modules/auth/forgot/hooks.ts
  apps/kg/modules/auth/forgot/module.tsx
  apps/kg/modules/auth/forgot/store.ts
  apps/kg/modules/auth/forgot/types.d.ts
  apps/kg/modules/auth/login/module.tsx
Labels: enhancement, KG

#333 feature: view-profile, change password, and cv section kg
  apps/kg/modules/profile/const.ts
  apps/kg/modules/profile/index.ts
  apps/kg/modules/profile/module.tsx
  apps/kg/modules/profile/section/change-password/api.ts
  apps/kg/modules/profile/section/change-password/hooks.ts
  apps/kg/modules/profile/section/change-password/index.ts
  apps/kg/modules/profile/section/change-password/section.tsx
  apps/kg/modules/profile/section/change-password/types.d.ts
  apps/kg/modules/profile/section/cv-portofolio/index.ts
  apps/kg/modules/profile/section/cv-portofolio/section.tsx
  apps/kg/modules/profile/section/index.ts
  apps/kg/modules/profile/section/profile-edit/api.ts
  apps/kg/modules/profile/section/profile-edit/hooks.ts
  apps/kg/modules/profile/section/profile-edit/index.ts
  apps/kg/modules/profile/section/profile-edit/section.tsx
  apps/kg/modules/profile/section/profile-edit/store.ts
  apps/kg/modules/profile/section/profile-edit/types.d.ts
  apps/kg/modules/profile/section/reset-password/ResetPassword.tsx
  apps/kg/modules/profile/section/reset-password/index.ts
  apps/kg/modules/profile/section/view-profile/index.ts
  apps/kg/modules/profile/section/view-profile/section.tsx
  apps/kg/modules/profile/sidebar/index.ts
  apps/kg/modules/profile/sidebar/section.tsx
  apps/kg/pages/auth/forgot.tsx
  apps/kg/pages/diskusi-ruang/index.tsx
  apps/kg/pages/profile/cv-portofolio/index.tsx
  apps/kg/pages/profile/edit-profile/index.tsx
  apps/kg/pages/profile/index.tsx
  apps/kg/pages/profile/ubah-password/index.tsx
  apps/lxp/modules/profile/main/edit-profile/section.tsx
Labels: enhancement, KG

#335 feature: integrate get all certificate
  apps/kg/modules/assignment/api.ts
  apps/kg/modules/assignment/hooks.ts
  apps/kg/modules/assignment/module.tsx
  apps/kg/modules/assignment/section/content/content.tsx
  apps/kg/modules/assignment/types.d.ts
  apps/kg/modules/auth/forgot/module.tsx
  apps/kg/modules/auth/login/module.tsx
  apps/kg/modules/score-sertificate/api.ts
  apps/kg/modules/score-sertificate/hook.ts
  apps/kg/modules/score-sertificate/section/certificate/certificate.tsx
  apps/kg/modules/score-sertificate/type.d.ts
Labels: enhancement, KG

#337 feature : quiz take and quiz desc integration api
  apps/kg/modules/mystudy/mystudy-module/subject/section.tsx
  apps/kg/modules/mystudy/quiz/api.ts
  apps/kg/modules/mystudy/quiz/hooks.ts
  apps/kg/modules/mystudy/quiz/module.tsx
  apps/kg/modules/mystudy/quiz/take/api.ts
  apps/kg/modules/mystudy/quiz/take/hooks.ts
  apps/kg/modules/mystudy/quiz/take/module.tsx
  apps/kg/modules/mystudy/quiz/take/store.ts
  apps/kg/modules/mystudy/quiz/take/type.d.ts
  apps/kg/modules/mystudy/quiz/types.d.ts
  apps/kg/modules/mystudy/subject-details/module.tsx
  apps/kg/modules/mystudy/subject-details/session/session.tsx
  apps/kg/next.config.js
  apps/kg/pages/api/mystudy/quiz/index.ts
  apps/kg/pages/auth/forgot.tsx
  apps/kg/pages/studi-ku/[detail-matkul]/kuis/[quizId]/index.tsx
  apps/kg/pages/studi-ku/[detail-matkul]/kuis/ambil/[quizTakeId]/index.tsx
Labels: enhancement, KG

#338 feature: create and integrating reply-section discussion forum kg
  apps/kg/modules/discussion-room/content/CommentSection.tsx
  apps/kg/modules/discussion-room/content/ReplySection.tsx
  apps/kg/modules/discussion-room/content/post/modal/post-create/index.ts
  apps/kg/modules/discussion-room/content/post/modal/post-create/section.tsx
  apps/kg/modules/discussion-room/content/section.tsx
  apps/kg/modules/discussion-room/hooks.ts
  apps/kg/modules/discussion-room/stores.ts
  package-lock.json
Labels: enhancement, KG

#340 feature: add page choice feature on request page
  apps/cs/src/components/atoms/icons/ic-back.tsx
  apps/cs/src/components/atoms/icons/index.ts
  apps/cs/src/modules/report/grafik/index.tsx
  apps/cs/src/modules/report/grafik/loading.tsx
  apps/cs/src/modules/report/index.tsx
  apps/cs/src/modules/report/report-request/index.tsx
  apps/cs/src/modules/report/report-request/table.tsx
  apps/cs/src/modules/report/report-user/report.tsx
  apps/cs/src/modules/report/report-user/table.tsx
  apps/cs/src/modules/report/store.ts
  apps/cs/src/modules/report/type.d.ts
  apps/cs/src/modules/request/feature/choice-feature/index.tsx
  apps/cs/src/modules/request/feature/choice-feature/table.tsx
  apps/cs/src/modules/request/feature/request.tsx
  apps/cs/src/modules/user/add-data/add-data.tsx
  apps/cs/src/modules/user/edit-data/edit-data.tsx
  apps/cs/src/routers/index.tsx
Labels: enhancement, CS

#341 Feature : training plan integration
  apps/lxp/modules/profile/main/edit-profile/api.ts
  apps/lxp/modules/profile/main/edit-profile/hook.ts
  apps/lxp/modules/profile/main/edit-profile/section.tsx
  apps/lxp/modules/training-plan/main/main.tsx
  apps/lxp/modules/training-plan/main/store.ts
Labels: bug, enhancement, LXP

#352 Improvemrnt : Login Page UI LXP
  apps/lxp/modules/auth/login/module.tsx
  apps/lxp/pages/_app.tsx
  libs/modules/src/auth/layout.tsx
  libs/modules/src/auth/types.d.ts
Labels: enhancement, LXP

#360 fixing : anchor text click here to path page report user
  apps/cs/src/modules/report/report-request/index.tsx
  apps/cs/src/modules/request/process/index.tsx
  apps/cs/src/modules/request/result/index.tsx
  apps/sample/app/page.tsx
Labels: bug

#361 Feature : training contract integration
  apps/lxp/modules/training-information/content/api.ts
  apps/lxp/modules/training-information/content/detail/detail.tsx
  apps/lxp/modules/training-information/content/detail/index.ts
  apps/lxp/modules/training-information/content/detail/types.d.ts
  apps/lxp/modules/training-information/content/header/header.tsx
  apps/lxp/modules/training-information/content/header/index.ts
  apps/lxp/modules/training-information/content/header/loading.tsx
  apps/lxp/modules/training-information/content/header/store.ts
  apps/lxp/modules/training-information/content/header/types.d.ts
  apps/lxp/modules/training-information/content/hook.ts
  apps/lxp/modules/training-information/content/index.ts
  apps/lxp/modules/training-information/content/section.tsx
  apps/lxp/modules/training-information/content/store.ts
  apps/lxp/modules/training-information/content/table/index.ts
  apps/lxp/modules/training-information/content/table/store.ts
  apps/lxp/modules/training-information/content/table/table.tsx
  apps/lxp/modules/training-information/content/table/types.d.ts
  apps/lxp/modules/training-information/content/types.d.ts
  apps/lxp/modules/training-information/header/index.ts
  apps/lxp/modules/training-information/main/index.ts
  apps/lxp/modules/training-information/main/main.tsx
  apps/lxp/modules/training-information/main/table/table.tsx
  apps/lxp/modules/training-information/traning-information.tsx
  apps/lxp/modules/training-information/types.d.ts
  apps/lxp/modules/training-plan/main/main.tsx
  apps/lxp/services/types.d.ts
Labels: enhancement, LXP

#362 feature : semua fitur
  apps/kg/modules/semuafitur/section/Features.tsx
  apps/kg/modules/study-contract/details/components/alert/index.tsx
  apps/kg/modules/study-contract/details/components/alert/type.d.ts
  apps/kg/modules/study-contract/details/components/layout/index.tsx
  apps/kg/modules/study-contract/details/components/layout/type.d.ts
  apps/kg/modules/study-contract/details/draft-krs/tabel.tsx
  apps/kg/modules/study-contract/details/index.tsx
  apps/kg/modules/study-contract/details/kontrak-krs/index.tsx
  apps/kg/modules/study-contract/details/kontrak-krs/tabel.tsx
  apps/kg/modules/study-contract/details/konversi/index.tsx
  apps/kg/modules/study-contract/details/konversi/tabel.tsx
  apps/kg/modules/study-contract/details/pengajuan/index.tsx
  apps/kg/modules/study-contract/details/pengajuan/tabel.tsx
Labels: KG

#363 improvement: get integration assignment
  apps/kg/modules/assignment/api.ts
  apps/kg/modules/assignment/component/assignment-card.tsx
  apps/kg/modules/assignment/hooks.ts
  apps/kg/modules/assignment/module.tsx
  apps/kg/modules/assignment/section/content/content.tsx
  apps/kg/modules/assignment/types.d.ts
Labels: enhancement, KG

#364 feature: create quiz-take global state and api middleware
  apps/kg/modules/mystudy/mystudy-module/subject/section.tsx
  apps/kg/modules/mystudy/quiz/take/hooks.ts
  apps/kg/modules/mystudy/quiz/take/module.tsx
  apps/kg/modules/mystudy/quiz/take/store.ts
  apps/kg/modules/mystudy/quiz/take/type.d.ts
  apps/kg/modules/mystudy/subject-details/module.tsx
  apps/kg/pages/api/mystudy/quiz/take/index.ts
Labels: enhancement, KG

#368 bugfix : error lint kg coz wrong path baselayout
  apps/kg/modules/index.ts
  apps/kg/modules/landing-alternatif/feature/icons/feature-1.tsx
  apps/kg/modules/landing-alternatif/feature/icons/feature-2.tsx
  apps/kg/modules/landing-alternatif/feature/icons/feature-3.tsx
  apps/kg/modules/landing-alternatif/feature/icons/feature-4.tsx
  apps/kg/modules/landing-alternatif/feature/icons/feature-5.tsx
  apps/kg/modules/landing-alternatif/feature/icons/index.ts
  apps/kg/modules/landing-alternatif/feature/index.ts
  apps/kg/modules/landing-alternatif/feature/section.tsx
  apps/kg/modules/landing-alternatif/hero/assets/bg.svg
  apps/kg/modules/landing-alternatif/hero/assets/model.png
  apps/kg/modules/landing-alternatif/hero/index.ts
  apps/kg/modules/landing-alternatif/hero/section.tsx
  apps/kg/modules/landing-alternatif/index.ts
  apps/kg/modules/landing-alternatif/module.tsx
  apps/kg/modules/landing-alternatif/partner/assets/partner-1.png
  apps/kg/modules/landing-alternatif/partner/assets/partner-2.png
  apps/kg/modules/landing-alternatif/partner/assets/partner-3.png
  apps/kg/modules/landing-alternatif/partner/assets/partner-4.png
  apps/kg/modules/landing-alternatif/partner/assets/partner-5.png
  apps/kg/modules/landing-alternatif/partner/index.ts
  apps/kg/modules/landing-alternatif/partner/section.tsx
  apps/kg/modules/landing/banner/banner-2/section.tsx
  apps/kg/modules/landing/testimony/section.tsx
  apps/kg/modules/mystudy/assignment/index.tsx
  apps/kg/modules/semuafitur/assets/random.svg
  apps/kg/modules/semuafitur/assets/random2.svg
  apps/kg/modules/semuafitur/component/Card.tsx
  apps/kg/modules/semuafitur/section/Features.tsx
  apps/kg/pages/landing-alternatif/index.tsx
  libs/components/atoms/src/bread-crumb/index.tsx
  libs/components/molecules/src/navbar/section/top-nav/section.tsx
Labels: bug

#374 Feature : Ask join department
  apps/lxp/modules/training-information/content/header/api.ts
  apps/lxp/modules/training-information/content/header/header.tsx
  apps/lxp/modules/training-information/content/header/hook.ts
  apps/lxp/modules/training-information/content/header/types.d.ts
  apps/lxp/modules/training-information/content/section.tsx
Labels: enhancement, LXP

#375 Improvement: integration cs & add dependency react avatar
  apps/cs/public/assets/navbar/user.jpg
  apps/cs/public/assets/navbar/user.png
  apps/cs/public/assets/navbar/user.webp
  apps/cs/public/assets/quota/card1.svg
  apps/cs/public/assets/quota/card2.svg
  apps/cs/public/assets/quota/card3.svg
  apps/cs/public/assets/quota/card4.svg
  apps/cs/src/components/organisms/sidebar/index.tsx
  apps/cs/src/components/organisms/sidebar/profile/api.ts
  apps/cs/src/components/organisms/sidebar/profile/hooks.ts
  apps/cs/src/components/organisms/sidebar/profile/types.ts
  apps/cs/src/modules/auth/login/hooks.ts
  apps/cs/src/modules/auth/login/index.tsx
  apps/cs/src/modules/auth/middleware/guest.tsx
  apps/cs/src/modules/auth/middleware/index.ts
  apps/cs/src/modules/auth/middleware/protected.tsx
  apps/cs/src/modules/quota/alocation-quota.tsx
  apps/cs/src/modules/quota/api.ts
  apps/cs/src/modules/quota/history-alocation.tsx
  apps/cs/src/modules/quota/hooks.ts
  apps/cs/src/modules/quota/store.ts
  apps/cs/src/modules/quota/table.tsx
  apps/cs/src/modules/quota/types.ts
  apps/cs/src/modules/request/api.ts
  apps/cs/src/modules/request/feature/request.tsx
  apps/cs/src/modules/request/hooks.ts
  apps/cs/src/modules/request/process/table.tsx
  apps/cs/src/modules/request/result/table.tsx
  apps/cs/src/modules/request/store.ts
  apps/cs/src/modules/request/types.d.ts
  apps/cs/src/routers/index.tsx
  apps/cs/src/services/api.ts
  libs/utils/src/helper/index.ts
  libs/utils/src/index.ts
  package.json
  yarn.lock
Labels: documentation, CS

#379 migrate all guide and integration api my-training
  apps/lxp/modules/guide-guide book/assets/book.svg
  apps/lxp/modules/guide-guide book/assets/panduan-hero.svg
  apps/lxp/modules/guide-guide book/assets/play-button.svg
  apps/lxp/modules/guide-guide book/assets/search.svg
  apps/lxp/modules/guide-guide book/assets/video-player.svg
  apps/lxp/modules/guide-guide book/assets/video.svg
  apps/lxp/modules/guide-guide book/const.ts
  apps/lxp/modules/guide-guide book/hooks.ts
  apps/lxp/modules/guide-guide book/index.ts
  apps/lxp/modules/guide-guide book/loading.tsx
  apps/lxp/modules/guide-guide book/module.tsx
  apps/lxp/modules/guide-guide book/section/content/content.tsx
  apps/lxp/modules/guide-guide book/section/hero/hero.tsx
  apps/lxp/modules/guide-guide book/section/index.ts
  apps/lxp/modules/guide-guide book/store .ts
  apps/lxp/modules/guide-guide book/type.d.ts
  apps/lxp/modules/guide-guide dictinoary detail/assets/dictionary-empty.svg
  apps/lxp/modules/guide-guide dictinoary detail/assets/search.svg
  apps/lxp/modules/guide-guide dictinoary detail/constant.ts
  apps/lxp/modules/guide-guide dictinoary detail/hooks.ts
  apps/lxp/modules/guide-guide dictinoary detail/index.ts
  apps/lxp/modules/guide-guide dictinoary detail/module.tsx
  apps/lxp/modules/guide-guide dictinoary detail/section/content.tsx
  apps/lxp/modules/guide-guide dictinoary detail/section/sidebar.tsx
  apps/lxp/modules/guide-guide dictinoary detail/store.ts
  apps/lxp/modules/guide-guide dictinoary/assets/dictionary-empty.svg
  apps/lxp/modules/guide-guide dictinoary/assets/search.svg
  apps/lxp/modules/guide-guide dictinoary/constant.ts
  apps/lxp/modules/guide-guide dictinoary/hooks.ts
  apps/lxp/modules/guide-guide dictinoary/index.ts
  apps/lxp/modules/guide-guide dictinoary/module.tsx
  apps/lxp/modules/guide-guide dictinoary/section/content.tsx
  apps/lxp/modules/guide-guide dictinoary/section/sidebar.tsx
  apps/lxp/modules/guide-guide dictinoary/store.ts
  apps/lxp/modules/guide-guide video home/assets/panduan-hero.svg
  apps/lxp/modules/guide-guide video home/assets/play-button.svg
  apps/lxp/modules/guide-guide video home/assets/search.svg
  apps/lxp/modules/guide-guide video home/assets/video-player.svg
  apps/lxp/modules/guide-guide video home/assets/video.svg
  apps/lxp/modules/guide-guide video home/const.ts
  apps/lxp/modules/guide-guide video home/hooks.ts
  apps/lxp/modules/guide-guide video home/index.ts
  apps/lxp/modules/guide-guide video home/loading.tsx
  apps/lxp/modules/guide-guide video home/module.tsx
  apps/lxp/modules/guide-guide video home/section/content/content.tsx
  apps/lxp/modules/guide-guide video home/section/hero/hero.tsx
  apps/lxp/modules/guide-guide video home/section/index.ts
  apps/lxp/modules/guide-guide video home/store .ts
  apps/lxp/modules/guide-guide video home/type.d.ts
  apps/lxp/modules/guide-guide video/module.tsx
  apps/lxp/modules/my-training/api.ts
  apps/lxp/modules/my-training/hooks.ts
  apps/lxp/modules/my-training/section/ContentSection.tsx
  apps/lxp/modules/my-training/section/HeroSection.tsx
  apps/lxp/modules/my-training/type.d.ts
  apps/lxp/pages/panduan/buku-panduan/index.tsx
  apps/lxp/pages/panduan/kamus/[slug]/index.tsx
  apps/lxp/pages/panduan/kamus/index.tsx
  apps/lxp/pages/panduan/video-panduan/index.tsx
Labels: LXP

#380 Improvement : register button and form input placeholder
  apps/lxp/modules/auth/login/module.tsx
  apps/lxp/modules/auth/register/module.tsx
  apps/lxp/modules/training-contract/main/main.tsx
  apps/lxp/modules/training-information/content/header/header.tsx
  apps/lxp/modules/training-information/content/index.ts
  apps/lxp/modules/training-information/index.ts
Labels: enhancement, LXP

#381 improvmeent: improvmenet avatar login
  libs/components/molecules/src/navbar/section/top-nav/section.tsx
Labels: enhancement, KG

#382 feature : login by google lxp
  apps/lxp/.env.example
  apps/lxp/modules/auth/login/types.d.ts
  apps/lxp/modules/auth/refresh-token/api.ts
  apps/lxp/modules/auth/refresh-token/types.ts
  apps/lxp/modules/training-plan/training-plan.tsx
  apps/lxp/modules/training-plan/unchoose/asset/icon.tsx
  apps/lxp/modules/training-plan/unchoose/asset/index.ts
  apps/lxp/modules/training-plan/unchoose/index.ts
  apps/lxp/modules/training-plan/unchoose/section.tsx
  apps/lxp/next.config.js
  apps/lxp/pages/api/auth/[...nextauth].ts
  apps/lxp/pages/auth/login.tsx
Labels: enhancement, LXP

#389 feature: migrate guide dictonary detail
  apps/kg/modules/guide/guide-dictionary-detail/constant.ts
  apps/kg/modules/guide/guide-dictionary-detail/content/content.tsx
  apps/kg/modules/guide/guide-dictionary-detail/content/index.ts
  apps/kg/modules/guide/guide-dictionary-detail/hooks.ts
  apps/kg/modules/guide/guide-dictionary-detail/index.ts
  apps/kg/modules/guide/guide-dictionary-detail/module.tsx
  apps/kg/modules/guide/guide-dictionary-detail/sidebar/index.ts
  apps/kg/modules/guide/guide-dictionary-detail/sidebar/sidebar.tsx
  apps/kg/modules/guide/guide-dictionary-detail/store.ts
  apps/kg/pages/panduan/kamus-kampus-gratis/[slug]/index.tsx
  libs/components/molecules/src/navbar/section/top-nav/section.tsx
  libs/components/molecules/src/navbar/section/top-nav/types.d.ts
  libs/components/molecules/src/navbar/types.ts
Labels: enhancement, KG

#396 Bufgix : improve ui and link
  apps/lxp/modules/auth/login/login-popup/login-popup.tsx
  apps/lxp/modules/common/footer/footer-layout/address/address.tsx
  apps/lxp/modules/common/footer/footer-layout/desc/desc.tsx
  apps/lxp/modules/common/provider/ClientProvider/provider.tsx
  apps/lxp/modules/discussion-room/content/post/modal/post-report-success/section.tsx
  apps/lxp/modules/discussion-room/content/post/modal/post-spam/section.tsx
Labels: bug, LXP

#398 feature : quiz-submit integration
  apps/kg/modules/mystudy/mystudy-module/subject/section.tsx
  apps/kg/modules/mystudy/quiz/take/api.ts
  apps/kg/modules/mystudy/quiz/take/components/quiz-timer/section.tsx
  apps/kg/modules/mystudy/quiz/take/components/quiz-timer/types.d.ts
  apps/kg/modules/mystudy/quiz/take/hooks.ts
  apps/kg/modules/mystudy/quiz/take/module.tsx
  apps/kg/modules/mystudy/quiz/take/type.d.ts
  apps/kg/modules/mystudy/subject-details/module.tsx
Labels: enhancement, KG

#399 feature : sekilas-ilmu and kontrak-krs
  apps/kg/modules/glimpse-knowledge/component/GlimpseKnowledgePage.tsx
  apps/kg/modules/glimpse-knowledge/component/Header/GlimpseKnowledgeHeader.tsx
  apps/kg/modules/glimpse-knowledge/component/Main/Card/GlimpseKnowledgeCard.tsx
  apps/kg/modules/glimpse-knowledge/component/Main/GlimpseKnowledgeMain.tsx
  apps/kg/modules/glimpse-knowledge/component/Main/Search/GlimpseKnowledgeMain.tsx
  apps/kg/modules/glimpse-knowledge/index.ts
  apps/kg/modules/glimpse-knowledge/layout/GlimpseKnowledgeLayoutPage.tsx
  apps/kg/modules/glimpse-knowledge/layout/Main/Card/RelatedGlimpseKnowledgeCard.tsx
  apps/kg/modules/glimpse-knowledge/layout/Main/GlimpseKnowledgeLayoutMain.tsx
  apps/kg/modules/glimpse-knowledge/layout/index.ts
  apps/kg/modules/glimpse-knowledge/layout/module.tsx
  apps/kg/modules/glimpse-knowledge/module.tsx
  apps/kg/modules/study-contract/index.tsx
  apps/kg/modules/study-plan/study-program/StudyProgram.tsx
  apps/kg/pages/kontrak-krs/[matkul]/detail/index.tsx
  apps/kg/pages/kontrak-krs/[matkul]/index.tsx
  apps/kg/pages/sekilas-ilmu/index.tsx
Labels: enhancement, KG

#400 Improvement: empty assignment
  apps/kg/middleware.ts
  apps/kg/modules/assignment/module.tsx
  apps/kg/modules/assignment/section/content/content.tsx
  apps/kg/modules/assignment/section/content/empty.tsx
  apps/kg/modules/assignment/section/content/error.tsx
  apps/kg/modules/assignment/section/content/ilustration/people.tsx
  apps/kg/modules/drill-simulasi/module.tsx
  apps/kg/modules/drill-simulasi/section/content/simulasion/history.tsx
  apps/kg/modules/drill-simulasi/section/content/simulasion/submisson.tsx
  apps/kg/modules/leaderboard/module.tsx
  apps/kg/modules/score-sertificate/main.tsx
  libs/components/atoms/src/bread-crumb/index.tsx
  libs/components/atoms/src/bread-crumb/types.d.ts
Labels: enhancement, KG

#403 improvement : integration quota page for select option, search and da…
  apps/cs/src/components/atoms/search/types.d.ts
  apps/cs/src/components/molecules/input/date-range-picker/index.tsx
  apps/cs/src/modules/common/hooks.ts
  apps/cs/src/modules/quota/alocation-quota.tsx
  apps/cs/src/modules/quota/api.ts
  apps/cs/src/modules/quota/history-alocation.tsx
  apps/cs/src/modules/quota/hooks.ts
  apps/cs/src/modules/quota/store.ts
  apps/cs/src/modules/quota/table.tsx
  apps/cs/src/modules/quota/types.ts
  libs/utils/src/helper/index.ts
Labels: documentation, CS

#404 Feature/training contract integration
  apps/lxp/modules/common/provider/ClientProvider/provider.tsx
  apps/lxp/modules/profile/api.ts
  apps/lxp/modules/profile/main/edit-profile/section.tsx
  apps/lxp/modules/profile/types.d.ts
  apps/lxp/modules/training-information/content/api.ts
  apps/lxp/modules/training-information/content/header/header.tsx
  apps/lxp/modules/training-information/content/header/store.ts
  apps/lxp/modules/training-information/content/header/types.d.ts
  apps/lxp/modules/training-information/content/hook.ts
  apps/lxp/modules/training-information/content/section.tsx
  apps/lxp/modules/training-information/content/store.ts
  apps/lxp/modules/training-information/content/types.d.ts
  apps/lxp/modules/training-information/traning-information.tsx
  apps/lxp/modules/training-plan/api.ts
  apps/lxp/modules/training-plan/hook.ts
  apps/lxp/modules/training-plan/index.ts
  apps/lxp/modules/training-plan/main/api.ts
  apps/lxp/modules/training-plan/main/hook.ts
  apps/lxp/modules/training-plan/main/types.d.ts
  apps/lxp/modules/training-plan/store.ts
  apps/lxp/modules/training-plan/taken/api.ts
  apps/lxp/modules/training-plan/taken/hook.ts
  apps/lxp/modules/training-plan/taken/index.ts
  apps/lxp/modules/training-plan/taken/section.tsx
  apps/lxp/modules/training-plan/taken/store.ts
  apps/lxp/modules/training-plan/taken/types.d.ts
  apps/lxp/modules/training-plan/training-plan.tsx
  apps/lxp/modules/training-plan/types.d.ts
  apps/lxp/modules/training-plan/unchoose/section.tsx
  apps/lxp/pages/auth/otp.tsx
Labels: enhancement, LXP

#411 fix : layout date picker on report page and quota page
  apps/cs/src/components/molecules/input/date-range-picker/index.tsx
  apps/cs/src/modules/quota/history-alocation.tsx
  apps/cs/src/modules/report/report-user/report.tsx
Labels: bug

#415 imporvement: integration get certificate
  apps/kg/modules/score-sertificate/section/certificate/certificate.tsx
  apps/kg/modules/score-sertificate/type.d.ts
Labels: enhancement, KG

#418 improvement : create section advantage
  apps/kg/modules/auth/login/module.tsx
  apps/kg/modules/landing-alternatif/advantage/assets/checlist.svg
  apps/kg/modules/landing-alternatif/advantage/assets/model.png
  apps/kg/modules/landing-alternatif/advantage/section.tsx
  apps/kg/modules/landing-alternatif/banner/banner-4/section.tsx
  apps/kg/modules/landing-alternatif/faculty/section.tsx
  apps/kg/modules/landing-alternatif/module.tsx
  apps/kg/modules/landing-alternatif/testimony/card/testi1.tsx
  apps/kg/modules/landing-alternatif/testimony/card/testi2.tsx
  apps/kg/pages/index.tsx
Labels: documentation

#424 Improvement : integration cs get user page project credit scoring
  apps/cs/src/modules/user/api.ts
  apps/cs/src/modules/user/hooks.ts
  apps/cs/src/modules/user/table.tsx
  apps/cs/src/modules/user/types.ts
  apps/kg/modules/landing-alternatif/feature/section.tsx
Labels: documentation, CS

#426 create popup forgot password and off darkmode
  apps/lxp/modules/auth/forgot/api.ts
  apps/lxp/modules/auth/forgot/hooks.ts
  apps/lxp/modules/auth/forgot/index.ts
  apps/lxp/modules/auth/forgot/module.tsx
  apps/lxp/modules/auth/forgot/store.ts
  apps/lxp/modules/auth/forgot/types.d.ts
  apps/lxp/modules/auth/login/module.tsx
  apps/lxp/tailwind.config.js
Labels: LXP

#437 Improvement: integrate get leaderboard
  apps/kg/modules/leaderboard/components/popup-profil.tsx
  apps/kg/modules/leaderboard/components/type.d.ts
  apps/kg/modules/leaderboard/hooks.ts
  apps/kg/modules/leaderboard/section/ranking-bottom.tsx
  apps/kg/modules/leaderboard/section/ranking-up.tsx
  apps/kg/modules/leaderboard/store.ts
  apps/kg/modules/leaderboard/type.d.ts
Labels: enhancement, KG

#438 improvement : integration functional search on user page and clear type,hooks and store dummy data
  apps/cs/src/modules/quota/alocation-quota.tsx
  apps/cs/src/modules/quota/history-alocation.tsx
  apps/cs/src/modules/quota/store.ts
  apps/cs/src/modules/quota/types.ts
  apps/cs/src/modules/user/hooks.ts
  apps/cs/src/modules/user/index.tsx
  apps/cs/src/modules/user/store.ts
  apps/cs/src/modules/user/types.d.ts
Labels: documentation, CS

#439 feature : integrasi kontrak KRS
  apps/kg/modules/study-contract/submissionContractStudy/api.ts
  apps/kg/modules/study-contract/submissionContractStudy/hook.ts
  apps/kg/modules/study-contract/submissionContractStudy/kontrak.tsx
  apps/kg/modules/study-contract/submissionContractStudy/store.ts
  apps/kg/modules/study-contract/submissionContractStudy/type.d.ts
  apps/kg/modules/study-plan/study-program/StudyProgram.tsx
Labels: enhancement, KG

#440 fix : fetch user data response
  apps/lxp/modules/common/provider/ClientProvider/provider.tsx
  apps/lxp/modules/profile/main/edit-profile/section.tsx
  apps/lxp/modules/profile/types.d.ts
Labels: bug, enhancement

#442 Feature : create page distribution of work
  apps/kg/modules/administration/constant.ts
  apps/kg/modules/common/layout/base/section.tsx
  apps/kg/modules/consultasion-and-service/const.ts
  apps/kg/modules/consultasion-and-service/icon/consultasion.svg
  apps/kg/modules/consultasion-and-service/icon/ic-service.svg
  apps/kg/modules/consultasion-and-service/icon/option.svg
  apps/kg/modules/consultasion-and-service/icon/random.svg
  apps/kg/modules/consultasion-and-service/icon/service.svg
  apps/kg/modules/consultasion-and-service/icon/star.svg
  apps/kg/modules/consultasion-and-service/index.ts
  apps/kg/modules/consultasion-and-service/section.tsx
  apps/kg/modules/discussion-room/hero/section.tsx
  apps/kg/modules/discussion-room/module.tsx
  apps/kg/modules/distribution-of-work/assets/gojek.svg
  apps/kg/modules/distribution-of-work/assets/google.svg
  apps/kg/modules/distribution-of-work/assets/mayora.svg
  apps/kg/modules/distribution-of-work/assets/search.svg
  apps/kg/modules/distribution-of-work/card/mitra1.tsx
  apps/kg/modules/distribution-of-work/card/mitra2.tsx
  apps/kg/modules/distribution-of-work/card/mitra3.tsx
  apps/kg/modules/distribution-of-work/const.ts
  apps/kg/modules/distribution-of-work/index.ts
  apps/kg/modules/distribution-of-work/module.tsx
  apps/kg/modules/guide/landing/hero/hero.tsx
  apps/kg/modules/index.ts
  apps/kg/modules/semuafitur/store.ts
  apps/kg/pages/konsultasi-dan-layanan/index.tsx
  apps/kg/pages/penyaluran-kerja/index.tsx
  libs/components/molecules/src/navbar/section/top-nav/section.tsx
Labels: documentation, enhancement

#448 Improvment : 403 Forbiden on training plan redirect to administration
  apps/lxp/modules/training-plan/hook.ts
  apps/lxp/modules/training-plan/main/hook.ts
  apps/lxp/modules/training-plan/taken/hook.ts
  libs/utils/src/types/index.ts
Labels: enhancement, LXP

#449 bugfix : undifined data cause by missing return
  apps/lxp/modules/training-plan/main/api.ts
  apps/lxp/modules/training-plan/main/hook.ts
  apps/lxp/modules/training-plan/main/main.tsx
Labels: bug, enhancement, LXP

#453 feature: integration getDiscussionById kg
  apps/kg/modules/discussion-room/content/api.ts
  apps/kg/modules/discussion-room/content/hooks.ts
  apps/kg/modules/discussion-room/content/post/modal/post-edit/hooks.ts
  apps/kg/modules/discussion-room/content/post/modal/post-edit/section.tsx
  apps/kg/modules/discussion-room/content/post/option/section.tsx
  apps/kg/modules/discussion-room/content/section.tsx
  apps/kg/modules/mystudy/discussion/module.tsx
  apps/kg/modules/mystudy/discussion/section/content/api.ts
  apps/kg/modules/mystudy/discussion/section/content/content.tsx
  apps/kg/modules/mystudy/discussion/section/content/hooks.ts
  apps/kg/modules/mystudy/discussion/section/content/types.d.ts
  apps/kg/pages/studi-ku/[detail-matkul]/diskusi/[id].tsx
Labels: enhancement, KG

#454 improvement : quiz home ui and routing by id
  apps/lxp/modules/mytraining-quiz/home/QuizHome.tsx
  apps/lxp/modules/mytraining-quiz/index.ts
  apps/lxp/modules/mytraining-quiz/module.tsx
  apps/lxp/pages/pelatihanku/quiz/[quiz_id].tsx
  yarn.lock
Labels: enhancement, LXP

#457 feature : create new page and pop-up in quiz
  apps/kg/modules/mystudy/quiz/assets/confirm.svg
  apps/kg/modules/mystudy/quiz/assets/warning.svg
  apps/kg/modules/mystudy/quiz/common/components/detail-card/section.tsx
  apps/kg/modules/mystudy/quiz/common/components/detail-card/types.d.ts
  apps/kg/modules/mystudy/quiz/history/api.ts
  apps/kg/modules/mystudy/quiz/history/components/history-card/card.tsx
  apps/kg/modules/mystudy/quiz/history/components/history-card/index.ts
  apps/kg/modules/mystudy/quiz/history/components/history-card/section.tsx
  apps/kg/modules/mystudy/quiz/history/hooks.ts
  apps/kg/modules/mystudy/quiz/history/module.tsx
  apps/kg/modules/mystudy/quiz/history/types.d.ts
  apps/kg/modules/mystudy/quiz/module.tsx
  apps/kg/modules/mystudy/quiz/review/api.ts
  apps/kg/modules/mystudy/quiz/review/const.ts
  apps/kg/modules/mystudy/quiz/review/hooks.ts
  apps/kg/modules/mystudy/quiz/review/index.ts
  apps/kg/modules/mystudy/quiz/review/module.tsx
  apps/kg/modules/mystudy/quiz/review/store.ts
  apps/kg/modules/mystudy/quiz/review/types.d.ts
  apps/kg/modules/mystudy/quiz/score/api.ts
  apps/kg/modules/mystudy/quiz/score/hooks.ts
  apps/kg/modules/mystudy/quiz/score/module.tsx
  apps/kg/modules/mystudy/quiz/score/types.d.ts
  apps/kg/modules/mystudy/quiz/take/components/bread-crumb/bread-crumb.tsx
  apps/kg/modules/mystudy/quiz/take/components/bread-crumb/index.ts
  apps/kg/modules/mystudy/quiz/take/components/pop-up/custom/index.ts
  apps/kg/modules/mystudy/quiz/take/components/pop-up/custom/pop-up.tsx
  apps/kg/modules/mystudy/quiz/take/components/pop-up/custom/types.d.ts
  apps/kg/modules/mystudy/quiz/take/components/pop-up/quit/hooks.ts
  apps/kg/modules/mystudy/quiz/take/components/pop-up/quit/index.ts
  apps/kg/modules/mystudy/quiz/take/components/pop-up/quit/pop-up.tsx
  apps/kg/modules/mystudy/quiz/take/components/pop-up/quit/store.ts
  apps/kg/modules/mystudy/quiz/take/components/pop-up/quit/types.d.ts
  apps/kg/modules/mystudy/quiz/take/components/pop-up/submit/hooks.ts
  apps/kg/modules/mystudy/quiz/take/components/pop-up/submit/index.ts
  apps/kg/modules/mystudy/quiz/take/components/pop-up/submit/pop-up.tsx
  apps/kg/modules/mystudy/quiz/take/components/pop-up/submit/store.ts
  apps/kg/modules/mystudy/quiz/take/components/pop-up/submit/types.d.ts
  apps/kg/modules/mystudy/quiz/take/components/quiz-timer/hooks.ts
  apps/kg/modules/mystudy/quiz/take/components/quiz-timer/section.tsx
  apps/kg/modules/mystudy/quiz/take/components/quiz-timer/types.d.ts
  apps/kg/modules/mystudy/quiz/take/components/static-timer/hooks.ts
  apps/kg/modules/mystudy/quiz/take/components/static-timer/index.ts
  apps/kg/modules/mystudy/quiz/take/components/static-timer/store.ts
  apps/kg/modules/mystudy/quiz/take/components/static-timer/timer.tsx
  apps/kg/modules/mystudy/quiz/take/components/static-timer/types.d.ts
  apps/kg/modules/mystudy/quiz/take/hooks.ts
  apps/kg/modules/mystudy/quiz/take/module.tsx
  apps/kg/modules/mystudy/quiz/take/return/hooks.ts
  apps/kg/modules/mystudy/quiz/take/return/section.tsx
  apps/kg/modules/mystudy/quiz/take/return/store.ts
  apps/kg/modules/mystudy/quiz/take/return/types.d.ts
  apps/kg/pages/api/mystudy/quiz/history/index.ts
  apps/kg/pages/api/mystudy/quiz/review/index.ts
  apps/kg/pages/api/mystudy/quiz/score/index.ts
  apps/kg/pages/studi-ku/[detail-matkul]/kuis/[quizId]/ambil/[quizTakeId]/index.tsx
  apps/kg/pages/studi-ku/[detail-matkul]/kuis/[quizId]/review/[quizReviewId]/index.tsx
  apps/kg/pages/studi-ku/[detail-matkul]/kuis/[quizId]/riwayat/[quizHistoryId]/index.tsx
  apps/kg/pages/studi-ku/[detail-matkul]/kuis/[quizId]/skor/[quizScoreId]/index.tsx
Labels: enhancement, KG

#465 Improvement : change table manual to react-data-table-component
  apps/cs/src/modules/report/report-request/index.tsx
  apps/cs/src/modules/report/report-request/table.tsx
  apps/cs/src/modules/report/report-user/report.tsx
  apps/cs/src/modules/report/report-user/table.tsx
  apps/cs/src/modules/user/add-data/api.ts
  apps/cs/src/modules/user/index.tsx
  apps/cs/src/modules/user/table.tsx
  apps/cs/src/modules/user/types.ts
Labels: documentation

#452 improvement: round ipk and add type poin
  apps/kg/modules/leaderboard/components/popup-profil.tsx
  apps/kg/modules/leaderboard/components/type.d.ts
  apps/kg/modules/leaderboard/section/ranking-bottom.tsx
  apps/kg/modules/leaderboard/section/ranking-up.tsx
  apps/kg/modules/leaderboard/store.ts
  apps/kg/modules/leaderboard/type.d.ts
Labels: enhancement, KG

#472 feature: integrating commentReply and create commentReply lxp
  apps/lxp/modules/my-training-discussion/common/cardAuthor.tsx
  apps/lxp/modules/my-training-discussion/section/CommentSection.tsx
  apps/lxp/modules/my-training-discussion/section/ReplySection.tsx
  apps/lxp/modules/my-training-discussion/section/api.ts
  apps/lxp/modules/my-training-discussion/section/content.tsx
  apps/lxp/modules/my-training-discussion/section/hooks.ts
  apps/lxp/modules/my-training-discussion/section/types.d.ts
  apps/lxp/modules/my-training-discussion/type.d.ts
Labels: enhancement, LXP

#474 Improvement : integration add data user page
  apps/cs/src/components/organisms/sidebar/index.tsx
  apps/cs/src/components/organisms/sidebar/profile/hooks.ts
  apps/cs/src/modules/common/hooks.ts
  apps/cs/src/modules/user/add-data/ai-capability-scoring/index.tsx
  apps/cs/src/modules/user/add-data/ai-character-scoring/index.tsx
  apps/cs/src/modules/user/add-data/ai-identity-scoring/index.tsx
  apps/cs/src/modules/user/add-data/api.ts
  apps/cs/src/modules/user/add-data/hooks.ts
  apps/cs/src/modules/user/add-data/types.ts
Labels: documentation

#478 feature : show quiz question and total question
  apps/lxp/modules/common/provider/ClientProvider/const.ts
  apps/lxp/modules/common/provider/ClientProvider/provider.tsx
  apps/lxp/modules/mytraining-quiz/section/StartQuiz/Count.tsx
  apps/lxp/modules/mytraining-quiz/section/StartQuiz/Question.tsx
  apps/lxp/modules/mytraining-quiz/section/StartQuiz/module.tsx
  apps/lxp/modules/mytraining-quiz/section/StartQuiz/store.ts
  libs/components/molecules/src/navbar/section/top-nav/dropdown-menu/menu.tsx
  libs/components/molecules/src/navbar/section/top-nav/section.tsx
Labels: enhancement, LXP

#471 Improvement: const administration and index number leaderboard
  apps/kg/modules/administration/api.ts
  apps/kg/modules/administration/common/section.tsx
  apps/kg/modules/administration/constant.ts
  apps/kg/modules/administration/hooks.ts
  apps/kg/modules/administration/jobs-information/index.tsx
  apps/kg/modules/administration/private-information/index.tsx
  apps/kg/modules/administration/types.d.ts
  apps/kg/modules/leaderboard/components/popup-profil.tsx
  apps/kg/modules/leaderboard/section/ranking-bottom.tsx
  libs/components/atoms/src/inputs/select/types.d.ts
Labels: enhancement, KG
